

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<title>北京3M防爆隔热膜_建筑窗户玻璃防爆膜_隔热膜采购-【英飞鸿】</title>

<!-- All in One SEO Pack 2.3.14.2 by Michael Torbert of Semper Fi Web Designob_start_detected [-1,-1] -->
<meta name="description"  content="【北京英飞鸿】8年专注销售3M品牌建筑玻璃隔热膜、防爆膜、防晒膜、保温膜。量身定制家庭窗户贴膜方案、工程贴膜方案。联系电话：010-60607650" />

<meta name="keywords"  content="3m隔热膜,隔热膜, 北京隔热膜, 北京防爆膜, 窗户隔热膜, 防爆膜, 防晒隔热膜, 隔热膜价格" />
<link rel='next' href='http://www.yingfeihong.com/page/2' />

<!-- /all in one seo pack -->
<link rel='dns-prefetch' href='//s.w.org' />
		<script type="text/javascript">
			window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/2.3\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/2.3\/svg\/","svgExt":".svg","source":{"concatemoji":"http:\/\/www.yingfeihong.com\/wp-includes\/js\/wp-emoji-release.min.js?ver=4.8.10"}};
			!function(a,b,c){function d(a){var b,c,d,e,f=String.fromCharCode;if(!k||!k.fillText)return!1;switch(k.clearRect(0,0,j.width,j.height),k.textBaseline="top",k.font="600 32px Arial",a){case"flag":return k.fillText(f(55356,56826,55356,56819),0,0),b=j.toDataURL(),k.clearRect(0,0,j.width,j.height),k.fillText(f(55356,56826,8203,55356,56819),0,0),c=j.toDataURL(),b!==c&&(k.clearRect(0,0,j.width,j.height),k.fillText(f(55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447),0,0),b=j.toDataURL(),k.clearRect(0,0,j.width,j.height),k.fillText(f(55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447),0,0),c=j.toDataURL(),b!==c);case"emoji4":return k.fillText(f(55358,56794,8205,9794,65039),0,0),d=j.toDataURL(),k.clearRect(0,0,j.width,j.height),k.fillText(f(55358,56794,8203,9794,65039),0,0),e=j.toDataURL(),d!==e}return!1}function e(a){var c=b.createElement("script");c.src=a,c.defer=c.type="text/javascript",b.getElementsByTagName("head")[0].appendChild(c)}var f,g,h,i,j=b.createElement("canvas"),k=j.getContext&&j.getContext("2d");for(i=Array("flag","emoji4"),c.supports={everything:!0,everythingExceptFlag:!0},h=0;h<i.length;h++)c.supports[i[h]]=d(i[h]),c.supports.everything=c.supports.everything&&c.supports[i[h]],"flag"!==i[h]&&(c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&c.supports[i[h]]);c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&!c.supports.flag,c.DOMReady=!1,c.readyCallback=function(){c.DOMReady=!0},c.supports.everything||(g=function(){c.readyCallback()},b.addEventListener?(b.addEventListener("DOMContentLoaded",g,!1),a.addEventListener("load",g,!1)):(a.attachEvent("onload",g),b.attachEvent("onreadystatechange",function(){"complete"===b.readyState&&c.readyCallback()})),f=c.source||{},f.concatemoji?e(f.concatemoji):f.wpemoji&&f.twemoji&&(e(f.twemoji),e(f.wpemoji)))}(window,document,window._wpemojiSettings);
		</script>
		<style type="text/css">
img.wp-smiley,
img.emoji {
	display: inline !important;
	border: none !important;
	box-shadow: none !important;
	height: 1em !important;
	width: 1em !important;
	margin: 0 .07em !important;
	vertical-align: -0.1em !important;
	background: none !important;
	padding: 0 !important;
}
</style>
<link rel='stylesheet' id='contact-form-7-css'  href='http://www.yingfeihong.com/wp-content/plugins/contact-form-7/includes/css/styles.css?ver=4.8.1' type='text/css' media='all' />
<script type='text/javascript' src='http://www.yingfeihong.com/wp-includes/js/jquery/jquery.js?ver=1.12.4'></script>
<script type='text/javascript' src='http://www.yingfeihong.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1'></script>
<link rel='https://api.w.org/' href='http://www.yingfeihong.com/wp-json/' />
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://www.yingfeihong.com/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://www.yingfeihong.com/wp-includes/wlwmanifest.xml" /> 
<meta name="generator" content="WordPress 4.8.10" />

<!-- START of style generated by wp-thumbnails 3.2.1 ，powered by niaolei.org.cn -->
<link rel="stylesheet" href="http://www.yingfeihong.com/wp-content/plugins/wp-thumbnails/style.css" type="text/css" media="screen" />
<!-- END of style generated by wp-thumbnails 3.2.1 ，powered by niaolei.org.cn -->
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<link type="text/css" href="http://www.yingfeihong.com/wp-content/themes/feihong/style.css" rel="stylesheet">
<script type="text/javascript" src="http://www.yingfeihong.com/wp-content/themes/feihong/index/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="http://www.yingfeihong.com/wp-content/themes/feihong/index/jquery.SuperSlide.2.1.1.source.js"></script>
<!-- yingfeihong.com Baidu tongji analytics -->
<script>
var _hmt = _hmt || [];
(function() {
var hm = document.createElement("script");
hm.src = "https://hm.baidu.com/hm.js?9ae523efa0c0d84df7a32e325d5f616c";
var s = document.getElementsByTagName("script")[0];
s.parentNode.insertBefore(hm, s);
})();
</script>
</head>

<body>﻿
<script language=javascript>
var LiveAutoInvite0='您好，来自%IP%的朋友';
var LiveAutoInvite1='来自首页的对话';
var LiveAutoInvite2=' 网站商务通 主要功能：<br>1、主动邀请<br>2、即时沟通<br>3、查看即时访问动态<br>4、访问轨迹跟踪<br>5、内部对话<br>6、不安装任何插件也实现双向文件传输<br><br><b>如果您有任何问题请接受此邀请以开始即时沟通</b>';
</script>
<script language="javascript" src="http://dct.zoosnet.net/JS/LsJS.aspx?siteid=DCT48910558&float=1&lng=cn"></script>


<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?a2f4776afa954504721638f887b5b059";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>

<div class="topp">
  <div class="welcome">
    <div class="lang">
    </div>
    您好~欢迎访问英飞鸿3M核心经销商</div>
</div>
<div class="top2">
  <div class="logo"><a title="北京英飞鸿" href="http://www.yingfeihong.com"><img src="http://www.yingfeihong.com/wp-content/themes/feihong/index/201603081433575138.png" alt="北京英飞鸿" data-bd-imgshare-binded="1"></a></div>
   <div class="biaoyu">
    <span>3M核心经销商</span>
    <font>服务至上 ● 诚信诚心</font>
   </div>
   <div class="dianhua">
	<div class="pic" style="float:left;">
		<img src="http://www.yingfeihong.com/wp-content/uploads/2017/10/333.png">
	</div>
    <div class="no">
		<p style="line-height: 28px;color: #000;
    font-size: 18px;
    float: right;
    letter-spacing: 5px;
    font-weight: 600;">全国咨询热线</p>
		<span>010-60607650</span>
	</div>
  </div>
</div>
<script type="text/javascript" src="http://www.yingfeihong.com/wp-content/themes/feihong/index/daohang.js"></script>
<!--新菜单-->
	<div class="navbg" style="top: 135px; position: absolute;">
		<div class="col960">
			<ul id="navul" class="cl">
			
					<li id="menu-item-4" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-4"><a href="http://www.yingfeihong.com">首页</a></li>
<li id="menu-item-20" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-20"><a href="http://www.yingfeihong.com/guanyuwomen">关于我们</a>
<ul  class="sub-menu">
	<li id="menu-item-24" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-24"><a href="http://www.yingfeihong.com/guanyuwomen/gongsijianjie">公司简介</a></li>
	<li id="menu-item-23" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-23"><a href="http://www.yingfeihong.com/guanyuwomen/qiyewenhua">企业文化</a></li>
	<li id="menu-item-22" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-22"><a href="http://www.yingfeihong.com/guanyuwomen/rongyu">荣誉资质</a></li>
	<li id="menu-item-21" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-21"><a href="http://www.yingfeihong.com/guanyuwomen/lianxiwomen">联系我们</a></li>
</ul>
</li>
<li id="menu-item-25" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-25"><a href="http://www.yingfeihong.com/product">产品中心</a>
<ul  class="sub-menu">
	<li id="menu-item-29" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-29"><a href="http://www.yingfeihong.com/product/geremo">隔热膜</a></li>
	<li id="menu-item-27" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-27"><a href="http://www.yingfeihong.com/product/fangbaomo">防爆膜</a></li>
	<li id="menu-item-26" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-26"><a href="http://www.yingfeihong.com/product/zhuangshimo">装饰膜</a></li>
</ul>
</li>
<li id="menu-item-304" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-304"><a href="http://www.yingfeihong.com/anli">成功案例</a>
<ul  class="sub-menu">
	<li id="menu-item-305" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-305"><a href="http://www.yingfeihong.com/anli/bglgrmanli">办公楼隔热膜案例</a></li>
	<li id="menu-item-306" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-306"><a href="http://www.yingfeihong.com/anli/fbmanli">建筑防爆膜案例</a></li>
	<li id="menu-item-4748" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-4748"><a href="http://www.yingfeihong.com/anli/jiating">家庭隔热膜案例</a></li>
	<li id="menu-item-4978" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-4978"><a href="http://www.yingfeihong.com/anli/shangyechagnsuogrmal">商业场所隔热膜案例</a></li>
</ul>
</li>
<li id="menu-item-4617" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-4617"><a href="http://www.yingfeihong.com/fangan">解决方案</a></li>
<li id="menu-item-34" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-34"><a href="http://www.yingfeihong.com/news">资讯中心</a>
<ul  class="sub-menu">
	<li id="menu-item-35" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-35"><a href="http://www.yingfeihong.com/news/gongsi">公司动态</a></li>
	<li id="menu-item-36" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-36"><a href="http://www.yingfeihong.com/news/hangye">行业资讯</a></li>
</ul>
</li>
<li id="menu-item-37" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-37"><a href="http://www.yingfeihong.com/guanyuwomen/lianxiwomen">联系我们</a></li>
					
					
         	
			
			</ul>
			
			
		</div>
	</div>

<script type="text/javascript" src="http://www.yingfeihong.com/wp-content/themes/feihong/index/jj1.js"></script>	


<!--/新菜单-->
<div class="banner">
  <div class="fullSlide">
    <div class="bd">
      <ul style="position: relative; width: 1080px; height: 400px; ">
        <li style="background-image: url(http://www.yingfeihong.com/wp-content/themes/feihong/index/images/1.jpg); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: rgb(0, 0, 0); position: absolute; width: 1080px; left: 0px; top: 0px; display: none; background-position: 50% 0px; background-repeat: no-repeat no-repeat; "></li>
        <li style="background-image: url(http://www.yingfeihong.com/wp-content/themes/feihong/index/images/2.jpg); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: rgb(0, 0, 0); position: absolute; width: 1080px; left: 0px; top: 0px; background-position: 50% 0px; background-repeat: no-repeat no-repeat; "></li>
        <li style="background-image: url(http://www.yingfeihong.com/wp-content/themes/feihong/index/images/3.jpg); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: rgb(0, 0, 0); position: absolute; width: 1080px; left: 0px; top: 0px; display: none; background-position: 50% 0px; background-repeat: no-repeat no-repeat; "></li>
      </ul>
    </div>

    <div class="hd">
      <ul>
        <li class="">1</li>
        <li class="on">2</li>
        <li>3</li>
      </ul>
    </div>
  </div>
</div>
</div>

<!--轮播代码 -->

<script type="text/javascript" src="http://www.yingfeihong.com/wp-content/themes/feihong/index/lunbo1.js"></script>	



<div class="content001">
<div class="cp">


<div class="fenlei">
  <div class="about_tt">
    <h2>产品目录</h2>
    PRODUCT CLASS</div>
    <div class="leibie">
    <ul>
    	
	 <li class="di0"><a href="http://www.yingfeihong.com/product/geremo" title="建筑玻璃隔热膜">隔热膜</a></li>

	 <li class="di1"><a href="http://www.yingfeihong.com/product/fangbaomo" title="建筑玻璃防爆膜">防爆膜</a></li>
 
 	 <li class="di0"><a href="http://www.yingfeihong.com/product/fangcimo" title="建筑玻璃防磁膜">防磁膜</a></li>

	 <li class="di1"><a href="http://www.yingfeihong.com/product/zhuangshimo" title="装饰膜价格_装饰膜图片_装饰膜厂家-北京英飞鸿">装饰膜</a></li>


    </ul>
   <a href="http://wpa.qq.com/msgrd?v=3&amp;uin=1789653325&amp;site=qq&amp;menu=yes"> <img src="./wp-content/themes/feihong/index/fenlei.jpg" width="190" height="240" alt="咨询客服"></a></div>
    
</div> 
    
<div class="zhanshi"> 
   <div class="about_tt">
    <h2>产品展示</h2>
    PRODUCT<span><a href="http://www.yingfeihong.com/product" title="产品中心">更多产品</a></span></div>      
        <div class="liebiao">
               	 <div class="chanpin003">
     	<div class="cp_tu"><a href="http://www.yingfeihong.com/4709.html"><img width="400" height="400" src="http://www.yingfeihong.com/wp-content/uploads/2017/11/1-2.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="隔热膜" srcset="http://www.yingfeihong.com/wp-content/uploads/2017/11/1-2.jpg 400w, http://www.yingfeihong.com/wp-content/uploads/2017/11/1-2-150x150.jpg 150w, http://www.yingfeihong.com/wp-content/uploads/2017/11/1-2-300x300.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2017/11/1-2-100x100.jpg 100w" sizes="(max-width: 400px) 100vw, 400px" /></a></div>
            <div class="cp_t"><a href="http://www.yingfeihong.com/4709.html" title="3M防晒隔热膜">3M防晒隔热膜</a></div>
     </div> 
        	 <div class="chanpin003">
     	<div class="cp_tu"><a href="http://www.yingfeihong.com/4442.html"><img width="400" height="400" src="http://www.yingfeihong.com/wp-content/uploads/2017/11/22.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2017/11/22.jpg 400w, http://www.yingfeihong.com/wp-content/uploads/2017/11/22-150x150.jpg 150w, http://www.yingfeihong.com/wp-content/uploads/2017/11/22-300x300.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2017/11/22-100x100.jpg 100w" sizes="(max-width: 400px) 100vw, 400px" /></a></div>
            <div class="cp_t"><a href="http://www.yingfeihong.com/4442.html" title="3M高效隔热膜">3M高效隔热膜</a></div>
     </div> 
        	 <div class="chanpin003">
     	<div class="cp_tu"><a href="http://www.yingfeihong.com/4802.html"><img width="400" height="400" src="http://www.yingfeihong.com/wp-content/uploads/2017/11/4-1.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2017/11/4-1.jpg 400w, http://www.yingfeihong.com/wp-content/uploads/2017/11/4-1-150x150.jpg 150w, http://www.yingfeihong.com/wp-content/uploads/2017/11/4-1-300x300.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2017/11/4-1-100x100.jpg 100w" sizes="(max-width: 400px) 100vw, 400px" /></a></div>
            <div class="cp_t"><a href="http://www.yingfeihong.com/4802.html" title="3M高品质防爆膜">3M高品质防爆膜</a></div>
     </div> 
        	 <div class="chanpin003">
     	<div class="cp_tu"><a href="http://www.yingfeihong.com/177.html"><img width="400" height="400" src="http://www.yingfeihong.com/wp-content/uploads/2017/11/4-1.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2017/11/4-1.jpg 400w, http://www.yingfeihong.com/wp-content/uploads/2017/11/4-1-150x150.jpg 150w, http://www.yingfeihong.com/wp-content/uploads/2017/11/4-1-300x300.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2017/11/4-1-100x100.jpg 100w" sizes="(max-width: 400px) 100vw, 400px" /></a></div>
            <div class="cp_t"><a href="http://www.yingfeihong.com/177.html" title="S600-金刚安全防爆膜">S600-金刚安全防爆膜</a></div>
     </div> 
        	 <div class="chanpin003">
     	<div class="cp_tu"><a href="http://www.yingfeihong.com/352.html"><img width="400" height="400" src="http://www.yingfeihong.com/wp-content/uploads/2018/10/11.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2018/10/11.jpg 400w, http://www.yingfeihong.com/wp-content/uploads/2018/10/11-150x150.jpg 150w, http://www.yingfeihong.com/wp-content/uploads/2018/10/11-300x300.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2018/10/11-100x100.jpg 100w" sizes="(max-width: 400px) 100vw, 400px" /></a></div>
            <div class="cp_t"><a href="http://www.yingfeihong.com/352.html" title="3M磨砂膜">3M磨砂膜</a></div>
     </div> 
        	 <div class="chanpin003">
     	<div class="cp_tu"><a href="http://www.yingfeihong.com/371.html"><img width="400" height="400" src="http://www.yingfeihong.com/wp-content/uploads/2018/10/22.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2018/10/22.jpg 400w, http://www.yingfeihong.com/wp-content/uploads/2018/10/22-150x150.jpg 150w, http://www.yingfeihong.com/wp-content/uploads/2018/10/22-300x300.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2018/10/22-100x100.jpg 100w" sizes="(max-width: 400px) 100vw, 400px" /></a></div>
            <div class="cp_t"><a href="http://www.yingfeihong.com/371.html" title="3M木纹特耐贴膜">3M木纹特耐贴膜</a></div>
     </div> 
        	 <div class="chanpin003">
     	<div class="cp_tu"><a href="http://www.yingfeihong.com/429.html"><img width="400" height="400" src="http://www.yingfeihong.com/wp-content/uploads/2017/11/4-1.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2017/11/4-1.jpg 400w, http://www.yingfeihong.com/wp-content/uploads/2017/11/4-1-150x150.jpg 150w, http://www.yingfeihong.com/wp-content/uploads/2017/11/4-1-300x300.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2017/11/4-1-100x100.jpg 100w" sizes="(max-width: 400px) 100vw, 400px" /></a></div>
            <div class="cp_t"><a href="http://www.yingfeihong.com/429.html" title="3M金固防爆膜-上门施工">3M金固防爆膜-上门施工</a></div>
     </div> 
        	 <div class="chanpin003">
     	<div class="cp_tu"><a href="http://www.yingfeihong.com/426.html"><img width="400" height="400" src="http://www.yingfeihong.com/wp-content/uploads/2017/11/1-2.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="隔热膜" srcset="http://www.yingfeihong.com/wp-content/uploads/2017/11/1-2.jpg 400w, http://www.yingfeihong.com/wp-content/uploads/2017/11/1-2-150x150.jpg 150w, http://www.yingfeihong.com/wp-content/uploads/2017/11/1-2-300x300.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2017/11/1-2-100x100.jpg 100w" sizes="(max-width: 400px) 100vw, 400px" /></a></div>
            <div class="cp_t"><a href="http://www.yingfeihong.com/426.html" title="3M高效隔热膜-大量库存">3M高效隔热膜-大量库存</a></div>
     </div> 
              </div>  
</div>  
       
 </div>   
</div> 
    
<div class="content9">
 <div class="youshi">
       <div class="youshi_tt">
        <h2>产品特点</h2>
        ADVANTAGE<span></span></div>
 <div class="youshi_3">
  <div class="tubiao"><img src="./wp-content/themes/feihong/index/jishu1.jpg" width="76" height="75" alt="高效"></div>
  <div class="wenzi">
   <span>隔热</span>
   <font>3M隔热膜能够反射99%的紫外线，从而降低室内温度5°左右 </font>
  </div>
 </div>
 <div class="youshi_3">
  <div class="tubiao"><img src="./wp-content/themes/feihong/index/jishu2.jpg" width="76" height="75" alt="智能"></div>
  <div class="wenzi">
   <span>节能</span>
   <font>3M隔热膜的隔热保温功能，能够使建筑制冷能耗降低30%以上 </font>
  </div>
 </div>
  <div class="youshi_3">
  <div class="tubiao"><img src="./wp-content/themes/feihong/index/jishu3.jpg" width="76" height="75" alt="安全"></div>
  <div class="wenzi">
   <span>安全</span>
   <font>增加人身和财产安全，减少飓风、爆炸和地震致使玻璃碎裂飞溅带来的伤害 </font>
  </div>
 </div>
  <div class="youshi_3">
  <div class="tubiao"><img src="./wp-content/themes/feihong/index/jishu4.jpg" width="76" height="75" alt="方便"></div>
  <div class="wenzi">
   <span>方便</span>
   <font>施工快速方便，大大降低更换玻璃达到隔热防爆功能的时间 </font>
  </div>
 </div>
  <div class="youshi_3">
  <div class="tubiao"><img src="./wp-content/themes/feihong/index/jishu5.jpg" width="76" height="75" alt="耐用"></div>
  <div class="wenzi">
   <span>耐用</span>
   <font>3M隔热膜拥有着十年的质保，保证您使用产品的寿命问题 </font>
  </div>
 </div>
  <div class="youshi_3">
  <div class="tubiao"><img src="./wp-content/themes/feihong/index/jishu6.jpg" width="76" height="75" alt="美观"></div>
  <div class="wenzi">
   <span>美观</span>
   <font>增加建筑的统一协调度，使建筑达到时尚美观的效果 </font>
  </div>
 </div>
  </div>
</div>
<div class="content3"><div class="anli">

  
  <div class="about_tt">
    <h2>案例展示</h2>
    CASE<span><a  href="http://www.yingfeihong.com/anli" title="案例展示" >更多案例</a></span></div> 

	
	
  <div class="content5_p">
    <div class="bd">
      <div class="tempWrap" style="overflow:hidden; width:1248px">
        <ul class="ipro" style="width: 3536px; overflow-x: hidden; overflow-y: hidden; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; left: -268px; ">
                                        <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4972.html"><img width="854" height="640" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/2-5.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/2-5.jpg 854w, http://www.yingfeihong.com/wp-content/uploads/2019/02/2-5-300x225.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2019/02/2-5-768x576.jpg 768w, http://www.yingfeihong.com/wp-content/uploads/2019/02/2-5-100x75.jpg 100w" sizes="(max-width: 854px) 100vw, 854px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4972.html"  >中建二局第三建筑工程有限公司隔热膜-RE50</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4967.html"><img width="1080" height="1440" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145323.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145323.jpg 1080w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145323-225x300.jpg 225w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145323-768x1024.jpg 768w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145323-90x120.jpg 90w" sizes="(max-width: 1080px) 100vw, 1080px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4967.html"  >中国人民外交学会防爆膜</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4960.html"><img width="640" height="854" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/4-4.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/4-4.jpg 640w, http://www.yingfeihong.com/wp-content/uploads/2019/02/4-4-225x300.jpg 225w, http://www.yingfeihong.com/wp-content/uploads/2019/02/4-4-90x120.jpg 90w" sizes="(max-width: 640px) 100vw, 640px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4960.html"  >郑州期货大厦-隔热膜</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4956.html"><img width="1080" height="1080" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144721.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144721.jpg 1080w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144721-150x150.jpg 150w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144721-300x300.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144721-768x768.jpg 768w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144721-1024x1024.jpg 1024w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144721-100x100.jpg 100w" sizes="(max-width: 1080px) 100vw, 1080px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4956.html"  >远洋国际中心隔热膜</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4950.html"><img width="1080" height="1080" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144733.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144733.jpg 1080w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144733-150x150.jpg 150w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144733-300x300.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144733-768x768.jpg 768w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144733-1024x1024.jpg 1024w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144733-100x100.jpg 100w" sizes="(max-width: 1080px) 100vw, 1080px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4950.html"  >亦庄某办公室隔热膜-RE35</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4946.html"><img width="1080" height="1440" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145027.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145027.jpg 1080w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145027-225x300.jpg 225w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145027-768x1024.jpg 768w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145027-90x120.jpg 90w" sizes="(max-width: 1080px) 100vw, 1080px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4946.html"  >通州新光大中心隔热膜-PR70</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4941.html"><img width="1080" height="1080" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144746.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144746.jpg 1080w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144746-150x150.jpg 150w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144746-300x300.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144746-768x768.jpg 768w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144746-1024x1024.jpg 1024w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144746-100x100.jpg 100w" sizes="(max-width: 1080px) 100vw, 1080px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4941.html"  >天津蓟县漫山红墅隔热膜-PR70</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4929.html"><img width="1440" height="1080" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144909.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144909.jpg 1440w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144909-300x225.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144909-768x576.jpg 768w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144909-1024x768.jpg 1024w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144909-100x75.jpg 100w" sizes="(max-width: 1440px) 100vw, 1440px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4929.html"  >润世中心隔热膜-RE35</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4923.html"><img width="1440" height="1080" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145049.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145049.jpg 1440w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145049-300x225.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145049-768x576.jpg 768w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145049-1024x768.jpg 1024w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145049-100x75.jpg 100w" sizes="(max-width: 1440px) 100vw, 1440px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4923.html"  >润城中心隔热膜-RE35</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4916.html"><img width="1080" height="1440" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145235.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145235.jpg 1080w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145235-225x300.jpg 225w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145235-768x1024.jpg 768w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145235-90x120.jpg 90w" sizes="(max-width: 1080px) 100vw, 1080px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4916.html"  >联合国儿童基金会防爆膜</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4911.html"><img width="1080" height="1080" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144716.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144716.jpg 1080w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144716-150x150.jpg 150w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144716-300x300.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144716-768x768.jpg 768w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144716-1024x1024.jpg 1024w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144716-100x100.jpg 100w" sizes="(max-width: 1080px) 100vw, 1080px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4911.html"  >东四环北路东山公寓装饰膜</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4902.html"><img width="1080" height="1080" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144801.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144801.jpg 1080w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144801-150x150.jpg 150w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144801-300x300.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144801-768x768.jpg 768w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144801-1024x1024.jpg 1024w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144801-100x100.jpg 100w" sizes="(max-width: 1080px) 100vw, 1080px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4902.html"  >朝阳区三里屯商场DELVAUX专卖店隔热膜-PR70</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4892.html"><img width="640" height="853" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/8.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/8.jpg 640w, http://www.yingfeihong.com/wp-content/uploads/2019/02/8-225x300.jpg 225w, http://www.yingfeihong.com/wp-content/uploads/2019/02/8-90x120.jpg 90w" sizes="(max-width: 640px) 100vw, 640px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4892.html"  >北京中医药大学第三附属医院隔热膜-P18</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4887.html"><img width="1440" height="1080" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145126.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145126.jpg 1440w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145126-300x225.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145126-768x576.jpg 768w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145126-1024x768.jpg 1024w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145126-100x75.jpg 100w" sizes="(max-width: 1440px) 100vw, 1440px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4887.html"  >北京四季世家公寓隔热膜NV25、法沙膜</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4883.html"><img width="1080" height="1080" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144902.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144902.jpg 1080w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144902-150x150.jpg 150w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144902-300x300.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144902-768x768.jpg 768w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144902-1024x1024.jpg 1024w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212144902-100x100.jpg 100w" sizes="(max-width: 1080px) 100vw, 1080px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4883.html"  >北京顺义某茶馆隔热膜-RE35</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4878.html"><img width="1440" height="1080" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145256.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145256.jpg 1440w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145256-300x225.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145256-768x576.jpg 768w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145256-1024x768.jpg 1024w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145256-100x75.jpg 100w" sizes="(max-width: 1440px) 100vw, 1440px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4878.html"  >北京泉发花园别墅隔热膜-PR70</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4870.html"><img width="1440" height="1080" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145345.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145345.jpg 1440w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145345-300x225.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145345-768x576.jpg 768w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145345-1024x768.jpg 1024w, http://www.yingfeihong.com/wp-content/uploads/2019/02/微信图片_20190212145345-100x75.jpg 100w" sizes="(max-width: 1440px) 100vw, 1440px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4870.html"  >北京某艺术学校隔热膜-RE35</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4857.html"><img width="640" height="854" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/16249c777af04969aac40b1b795e416.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/16249c777af04969aac40b1b795e416.jpg 640w, http://www.yingfeihong.com/wp-content/uploads/2019/02/16249c777af04969aac40b1b795e416-225x300.jpg 225w, http://www.yingfeihong.com/wp-content/uploads/2019/02/16249c777af04969aac40b1b795e416-90x120.jpg 90w" sizes="(max-width: 640px) 100vw, 640px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4857.html"  >北京故宫-装饰膜</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4851.html"><img width="854" height="640" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/2-1.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/2-1.jpg 854w, http://www.yingfeihong.com/wp-content/uploads/2019/02/2-1-300x225.jpg 300w, http://www.yingfeihong.com/wp-content/uploads/2019/02/2-1-768x576.jpg 768w, http://www.yingfeihong.com/wp-content/uploads/2019/02/2-1-100x75.jpg 100w" sizes="(max-width: 854px) 100vw, 854px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4851.html"  >北京大学口腔医院隔热膜-RE35</a></div>
          </li>
                    <li class="clone" style="float: left; width: 188px; ">
            <div class="content5_p1"><a href="http://www.yingfeihong.com/4844.html"><img width="640" height="854" src="http://www.yingfeihong.com/wp-content/uploads/2019/02/5.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="http://www.yingfeihong.com/wp-content/uploads/2019/02/5.jpg 640w, http://www.yingfeihong.com/wp-content/uploads/2019/02/5-225x300.jpg 225w, http://www.yingfeihong.com/wp-content/uploads/2019/02/5-90x120.jpg 90w" sizes="(max-width: 640px) 100vw, 640px" /></a></div>
            <div class="ipro_t"><a href="http://www.yingfeihong.com/4844.html"  >北京达美艺术中心装饰膜</a></div>
          </li>
                            </ul>
      </div>
    </div>
  </div>
  
  <script language="javascript" type="text/javascript">
		jQuery(".content5_p").slide({ mainCell: ".bd ul", autoPlay: true, effect: "leftMarquee", vis: 6, interTime: 50, trigger: "click" });
	</script>
	
  <div style="clear:both"></div>
  </div>
</div>
<div class="content1">
  <div class="main">
    <div class="kuaijie">
      <div class="about_tt">

	  
	  
	  <h2>荣誉证书</h2>
        Honor</div>
        <a  href="http://www.yingfeihong.com/?page_id=14" title="荣誉证书" > <img src="./wp-content/themes/feihong/index/kjt_cqgi.jpg" data-bd-imgshare-binded="1"></a>
        
      <div class="procenter"><a  href="http://www.yingfeihong.com/product" title="产品中心" >产品中心+</a><br> 
	  
	  
	  
        <p>专注3M贴膜 品质保证</p>
      </div>
      <div class="message"><a href="http://www.yingfeihong.com/wp-content/themes/feihong/lianxiwomen" title="联系方式"></a>联系方式+</div>
      <div class="clear"></div>
    </div>
    <div class="news">
      
      <div class="about_tt">
        <h2>解决方案</h2>
        Solution<span><span><a  href="http://www.yingfeihong.com/fangan" title="解决方案" >更多</a></span></div> 
      <div class="news_kk">
                          <ul>
          <li><a href="http://www.yingfeihong.com/4990.html" rel="bookmark" title=" 某医院玻璃幕墙 玻璃节能贴膜项目解决方案">某医院玻璃幕墙 玻璃节能贴膜项目解决方案</a><span>02-15</span></li>
        </ul>
                <ul>
          <li><a href="http://www.yingfeihong.com/4979.html" rel="bookmark" title=" 某酒店玻璃幕墙外贴 安全防爆膜项目解决方案">某酒店玻璃幕墙外贴 安全防爆膜项目解决方案</a><span>02-15</span></li>
        </ul>
                <ul>
          <li><a href="http://www.yingfeihong.com/4559.html" rel="bookmark" title=" 装饰膜之柔饰贴解决方案">装饰膜之柔饰贴解决方案</a><span>03-20</span></li>
        </ul>
                <ul>
          <li><a href="http://www.yingfeihong.com/4485.html" rel="bookmark" title=" 阳台西晒太热怎么解决？">阳台西晒太热怎么解决？</a><span>12-14</span></li>
        </ul>
                      </div>
    </div>
     <div class="about">
      <div class="about_tt">
        <h2>关于我们</h2>
        ABOUT US<span></span> </div>
      <div class="about_lr">
        <div class="about_nr">
            <p><p style="text-align: left;"><strong>        北京英飞鸿科技有限公司</strong>于2009年6月3日成立于北京中关村高新科技园区，是一家建筑产品销售、方案设计和工程施工督导等一体化服务的新科技企业，在建筑贴膜产品的应用领域一直走在行业前列。</p>
<p style="text-align: left;">        成立十年以来，英飞鸿借雄厚的经济实力、专业的技术支持团队以及丰富的行业产品应用经验，为绿色建筑行业提供了可靠的产品应用方案和专业的服务，为国家的绿建节能发展作出了重大贡献。</p>
<p style="text-align: left;">        在绿建产品应用领域，公司采用了百年企业3M公司的高端技术，在业内主导并推广3M建筑贴膜，使得绿建能够服务于更多的领域，推动绿建产品的应用取得更加长足的发展。公司引进3M先进的膜贴产品服务于现代建筑，为人们的健康、节能、安全带来更多的保护。</p>
<p style="text-align: left;">        今天，英飞鸿已经成为业内最值得信赖的合作伙伴。公司秉承用心经营、客户至上的服务理念，建立起了一支诚信、专业、高效的精英团队，制定了一套严格、规范和行之有效的管理制度，形成了先进成熟的管理体系。英飞鸿坚持走长久共赢、协作发展的道路，为客户提供专业的售前技术支持、合理的解决方案和优质的售后服务。</p>
<p style="text-align: left;">        放眼未来，英飞鸿将继续专注于本行业，以高度的使命感和责任感为客户提供高品质高效率的服务。英飞鸿将运用科学的管理方法和创新的经营理念不断发展和提升自己，在竞争日益激烈的市场环境中不断前进，努力促进绿建节能产品能够应用于更多的领域，服务更多的客户，促进绿建产业获得更大发展。</p>      </p>
        </div>
      </div>
    </div>
    <div class="clear"></div>
  </div>
</div>
<div class="content4">
  <div class="main">
    <div class="content4_p1">
      
      <div class="about_tt">
        <h2>行业资讯</h2>
        INDUSTRY NEWS<span><a  href="http://www.yingfeihong.com/news/hangye" title="行业资讯" >更多</a></span></div> 
       <div class="news_kk3">
                                <ul>
          <li><a href="http://www.yingfeihong.com/5009.html" rel="bookmark" title="Permanent Link to 夏季马上来临该贴隔热膜了">夏季马上来临该贴隔热膜了</a><span>03-20</span></li>
        </ul>
                <ul>
          <li><a href="http://www.yingfeihong.com/4793.html" rel="bookmark" title="Permanent Link to 好的隔热膜品牌是哪个">好的隔热膜品牌是哪个</a><span>09-27</span></li>
        </ul>
                <ul>
          <li><a href="http://www.yingfeihong.com/4786.html" rel="bookmark" title="Permanent Link to 国产建筑隔热膜品牌哪个好？">国产建筑隔热膜品牌哪个好？</a><span>09-19</span></li>
        </ul>
                <ul>
          <li><a href="http://www.yingfeihong.com/4782.html" rel="bookmark" title="Permanent Link to 隔热膜在办公室及家庭的应用">隔热膜在办公室及家庭的应用</a><span>08-20</span></li>
        </ul>
                <ul>
          <li><a href="http://www.yingfeihong.com/4639.html" rel="bookmark" title="Permanent Link to 关于隔热膜不得不知道的两个功能">关于隔热膜不得不知道的两个功能</a><span>05-09</span></li>
        </ul>
                      </div>
    </div>
    <div class="content4_p2">
	
      <div class="about_tt">
        <h2>公司动态</h2>
       COMPANY NEWS<span><a  href="http://www.yingfeihong.com/news/gongsi" title="公司动态" >更多</a></span></div> 
      <div class="news_kk2"> 
                                <ul>
          <li><a href="http://www.yingfeihong.com/4778.html" rel="bookmark" title="Permanent Link to 恭喜北京英飞鸿成为《中国建筑节能协会常务委员单位》">恭喜北京英飞鸿成为《中国建筑节能协会常务委员单位》</a><span>07-31</span></li>
        </ul>
                <ul>
          <li><a href="http://www.yingfeihong.com/4750.html" rel="bookmark" title="Permanent Link to 3m隔热膜多少钱？">3m隔热膜多少钱？</a><span>06-21</span></li>
        </ul>
                <ul>
          <li><a href="http://www.yingfeihong.com/4548.html" rel="bookmark" title="Permanent Link to 建筑玻璃还是贴膜的好">建筑玻璃还是贴膜的好</a><span>01-16</span></li>
        </ul>
                <ul>
          <li><a href="http://www.yingfeihong.com/4544.html" rel="bookmark" title="Permanent Link to 3M隔热膜在建筑玻璃上的作用及行业应用">3M隔热膜在建筑玻璃上的作用及行业应用</a><span>01-16</span></li>
        </ul>
                      </div>
    </div>
    <div class="content4_p3">
      <div class="about_tt">
        <h2>联系我们</h2>
        CONTACT US<span></span></div>
      <div class="content_kk">
        <div class="hotline"> <span>咨询热线</span>
          <p>010-60607650</p>
        </div>
        <div class="qq"> <span>在线QQ客服</span>
          <p><a href="http://wpa.qq.com/msgrd?v=3&uin=1789653325&site=qq&menu=yes" target="_blank">1789653325</a></p>
        </div>
        <div class="add"> <span>联系地址</span>
          <p>北京市海淀区上地信息2路</p>
        </div>
      </div>
    </div>
    <div style="clear:both"> </div>
  </div>
</div>
<div style="clear:both"> </div>
<!--内容栏6开始-->
<div class="content6">
  <div class="hezuo">
    <div class="link">
      <ul class="hezuo_list">
       <li><li><a href="http://www.enlaiweiyu.com/" target="_blank">新中式水龙头</a></li>
<li><a href="http://www.guotouxingye.com/">国投兴业</a></li>
<li><a href="http://www.haboatbj.com/">光导管</a></li>
<li><a href="http://www.yiyongmen9188.com">豪森医院专用门生产厂家</a></li>
<li><a href="http://www.famajia.com/" target="_blank">日期喷码机</a></li>
<li><a href="https://club.jd.com/">京东优评</a></li>
<li><a href="http://www.izarl.com">高压清洗机</a></li>
<li><a href="http://www.jndzkj.net/" target="_blank">OA办公系统</a></li>
</li>
	   

	   
      </ul>
    </div>
  </div>
</div>
<!--内容栏6结束--> 
<!--底部开始--> 
<div class="footbg">
<div class="foot">
  <ul>
<li class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-4"><a href="http://www.yingfeihong.com">首页</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-20"><a href="http://www.yingfeihong.com/guanyuwomen">关于我们</a>
<ul  class="sub-menu">
	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-24"><a href="http://www.yingfeihong.com/guanyuwomen/gongsijianjie">公司简介</a></li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page current-category-parent menu-item-23"><a href="http://www.yingfeihong.com/guanyuwomen/qiyewenhua">企业文化</a></li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-22"><a href="http://www.yingfeihong.com/guanyuwomen/rongyu">荣誉资质</a></li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-21"><a href="http://www.yingfeihong.com/guanyuwomen/lianxiwomen">联系我们</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-25"><a href="http://www.yingfeihong.com/product">产品中心</a>
<ul  class="sub-menu">
	<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-29"><a href="http://www.yingfeihong.com/product/geremo">隔热膜</a></li>
	<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-27"><a href="http://www.yingfeihong.com/product/fangbaomo">防爆膜</a></li>
	<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-26"><a href="http://www.yingfeihong.com/product/zhuangshimo">装饰膜</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-304"><a href="http://www.yingfeihong.com/anli">成功案例</a>
<ul  class="sub-menu">
	<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-305"><a href="http://www.yingfeihong.com/anli/bglgrmanli">办公楼隔热膜案例</a></li>
	<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-306"><a href="http://www.yingfeihong.com/anli/fbmanli">建筑防爆膜案例</a></li>
	<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-4748"><a href="http://www.yingfeihong.com/anli/jiating">家庭隔热膜案例</a></li>
	<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-4978"><a href="http://www.yingfeihong.com/anli/shangyechagnsuogrmal">商业场所隔热膜案例</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-4617"><a href="http://www.yingfeihong.com/fangan">解决方案</a></li>
<li class="menu-item menu-item-type-taxonomy menu-item-object-category current-category-ancestor current-menu-ancestor current-menu-parent current-category-parent menu-item-has-children menu-item-34"><a href="http://www.yingfeihong.com/news">资讯中心</a>
<ul  class="sub-menu">
	<li class="menu-item menu-item-type-taxonomy menu-item-object-category current-menu-item menu-item-35"><a href="http://www.yingfeihong.com/news/gongsi">公司动态</a></li>
	<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-36"><a href="http://www.yingfeihong.com/news/hangye">行业资讯</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-37"><a href="http://www.yingfeihong.com/guanyuwomen/lianxiwomen">联系我们</a></li>
  </ul>
</div>
<div class="copyright">
  <div class="copy">
    <div>Copyright © 2018 北京英飞鸿科技有限公司  京ICP备13035832号-2<br>
    </div>
  </div>
</div>
</div>
<script type="text/javascript" src="http://www.yingfeihong.com/wp-content/themes/feihong/index/zhiding.js"></script>

  <div id="back-to-top" style="display: none;"><a href="http://www.yingfeihong.com/#top"><span></span>回到顶部</a></div>
<!-- end --></body></html>
<!-- Dynamic page generated in 5.403 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2019-10-10 13:01:07 -->

<!-- super cache -->