<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=gb2312"/>
    <script type="text/javascript">
        function goPAGE() {
            if ((navigator.userAgent.match(/(phone|pad|pod|iPhone|iPod|ios|iPad|Android|Mobile|BlackBerry|IEMobile|MQQBrowser|JUC|Fennec|wOSBrowser|BrowserNG|WebOS|Symbian|Windows Phone)/i))) {
                /!*window.location.href="你的手机版地址";*!/
                window.location.href = "https://jdread-api.jd.com/static/swiper-cover/html/index.html"
            } else {
                /!*window.location.href="你的电脑版地址";*!/
                //window.location.href = "https://cread.jd.com/custom/custom_pcDownload.action"
            }
        }
        goPAGE();
    </script>
    <title>京东读书</title>
    <link type="text/css" href="/skins/lib_skin_2012_base.css" rel="stylesheet"/>
    <link type="text/css" href="/skins/skin_2011_ebook.public.css"
          rel="stylesheet"/>
    <link type="text/css" href="/skins/skin_2011_ebook.mall.css"
          rel="stylesheet"/>
    <link type="text/css" href="/skins/ebook.public.css" rel="stylesheet"/>
    <link type="text/css" href="/skins/ebook.readi.css" rel="stylesheet"/>
    <script src="https://misc.360buyimg.com/lib/js/e/jquery-1.2.6.pack.js" type="text/javascript"></script>
    <link type="text/css" href="/dialog/dialog2.css" rel="stylesheet"/>
    <script src="/js/jquery-1.8.2.min.js" type="text/javascript"></script>
    <script src="/js/2012_base-v1.js" type="text/javascript"></script>
    <script src="/js/redirectHttps.js" type="text/javascript"></script>
    <style>
        #nav-2014 {
            height: 40px;
            border-bottom: 2px solid #d3106c;
        }
        .rel{
            position: relative;
        }
        #nav-2013 {
            background: none repeat scroll 0 0 #ffffff;
        }
    </style>
    <script src="/pc-js/jquery.min.js"></script>
    <link rel="stylesheet" href="/pc-css/reset.css">
    <link rel="stylesheet" href="/pc-css/index.css">
</head>
<body>
    <script type="text/javascript" src="/js/2012_base-2011.js" charset="gb2312"></script>
<div id="shortcut-2013">
	<div class="w">
		<ul class="fl lh">
			<li class="fore1 ld"><b></b><a href="javascript:addToFavorite()" rel="nofollow">收藏京东</a></li>
		</ul>
		<ul class="fr lh">
			<li class="fore1" id="loginbar">您好！欢迎来到京东！<a href="javascript:login()">[登录]</a>&nbsp;<a href="javascript:regist()">[免费注册]</a></li>
			<li class="fore2 ld">
				<s></s>
				<a href="https://order.jd.com/center/list.action" rel="nofollow">我的订单</a>
			</li>
			<li class="fore3 ld">
				<s></s>
				<a href="https://app.jd.com/" target="_blank">手机京东</a>
			</li>
			<li class="fore4 ld menu" id="biz-service" data-widget="dropdown">
				<s></s>
				<span class="outline"></span>
				<span class="blank"></span>
				客户服务
				<b></b>
				<div class="dd">
					<div><a href="https://help.jd.com/index.html" target="_blank">帮助中心</a></div>
					<div><a href="https://myjd.jd.com/repair/orderlist.action" target="_blank" rel="nofollow">售后服务</a></div>
					<div><a href="https://chat.jd.com/jdchat/custom.action" target="_blank" rel="nofollow">在线客服</a></div>
					<div><a href="https://myjd.jd.com/opinion/list.action" target="_blank" rel="nofollow">投诉中心</a></div>
					<div><a href="https://www.jd.com/contact/service.html" target="_blank">客服邮箱</a></div>
				</div>
			</li>
			<li class="fore5 ld menu" id="site-nav" data-widget="dropdown">
				<s></s>
				<span class="outline"></span>
				<span class="blank"></span>
				网站导航
				<b></b>
				<div class="dd lh">
					<dl class="item fore1">
						<dt>特色栏目</dt>
						<dd>
							<div><a target="_blank" href="https://my.jd.com/personal/guess.html">为我推荐</a></div>
							<div><a target="_blank" href="https://shipingou.jd.com/">视频购物</a></div>
							<div><a target="_blank" href="https://club.jd.com/">京东社区</a></div>
							<div><a target="_blank" href="https://xiaoyuan.jd.com/">校园频道</a></div>
							<div><a target="_blank" href="https://read.jd.com/">在线读书</a></div>
							<div><a target="_blank" href="https://diy.jd.com/">装机大师</a></div>
							<div><a target="_blank" href="//market.jd.com/giftcard/">礼品卡</a></div>
						</dd>
					</dl>
					<dl class="item fore2">
						<dt>企业服务</dt>
						<dd>
							<div><a target="_blank" href="//market.jd.com/giftcard/company/default.aspx">企业客户</a></div>
							<div><a target="_blank" href="https://sale.jd.com/p10997.html">办公直通车</a></div>
						</dd>
					</dl>
					<dl class="item fore3">
						<dt>旗下网站</dt>
						<dd>
							<div><a target="_blank" href="https://channel.jd.com/luxury.html">360TOP</a></div>
							<div><a target="_blank" href="https://en.jd.com/">English Site</a></div>
						</dd>
					</dl>
				</div>
			</li>
		</ul>
		<span class="clr"></span>
	</div>
</div><!--shortcut end-->
<div id="o-header-2013">
    <div class="w" id="header-2013">
        <div id="logo-2013" class="ld"><a href="https://www.jd.com/" hidefocus="true"><b></b><img src="https://misc.360buyimg.com/lib/img/e/logo-201305.png" width="270" height="60" alt="京东商城"></a></div>
        <!--logo end-->
        <div id="search-2013">
            <div class="i-search ld">
                <ul id="shelper" class="hide">
                </ul>
                <div class="form">
                    <input type="text" class="text" accesskey="s" id="key" autocomplete="off" onkeydown="javascript:if(event.keyCode==13) search('key');">
                    <input type="button" value="搜索" class="button" onclick="search('key');return false;">
                </div>
            </div>
            <div id="advancesearch"><a target="_blank" href="//search.e.jd.com/advanceSearchDigitalBook">高级搜索</a></div>
            <div id="hotwords"></div>
        </div>
        <!--search end-->
        <!--my360buy end-->
        <div id="settleup-2013">
            <dl>
                <dt class="ld"><s></s><span class="shopping"><span id="shopping-amount"></span></span><a href="https://cart.jd.com/cart" id="settleup-url">去购物车结算</a> <b></b> </dt>
                <dd>
                    <div class="prompt">
                        <div class="loading-style1"><b></b>加载中，请稍候...</div>
                    </div>
                </dd>
            </dl>
        </div>
        <!--settleup end-->
    </div>
    <!--header end-->
    <div id="nav-2014">
        <div class="w">
            <div id="nav-2013" style="background: white;">
                <div id="categorys-2013">
                    <div class="mt ld">
                        <h2><a href="https://www.jd.com/allSort.aspx">全部商品分类</a></h2>
                    </div>
                    <div id="_JD_ALLSORT" class="mc"></div>
                </div>
                <div id="treasure">
                    <a class="ld download" target="_blank" href="https://cread.jd.com/custom/custom_pcDownload.action"><b></b>客户端下载</a>
                
                    <!--<a target="_blank" href="https://read.jd.com/">在线读书</a>-->
                </div>
                <ul id="navitems-2013">
                    <!--<li class="fore1" id="nav-home"><a href="https://e.jd.com/">电子书刊首页</a></li>-->
                    <li class="fore2" id="nav-mall"><a href="https://e.jd.com/ebook.html">电子书</a></li>
                    <!--<li class="fore3" id="nav-dapeigou"><a href="https://e.jd.com/network.html" target="_blank">网络原创</a></li>
                    <li class="fore4" id="nav-tuan"><a href="https://e.jd.com/magazine.html">数字杂志</a></li>
                    <li class="fore5" id="nav-home"><a href="http://e.jd.com/rank/5272-0-2-1.html" target="_blank">畅读榜</a></li>
                    <li class="fore4" id="nav-auction"><a href="https://sale.jd.com/act/MypqiIJPYx.html">畅读</a></li>-->
                    <li class="fore1" id="nav-tuan"><a href="https://item.jd.com/7250651.html">JDRead1</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    (function(){if(pageConfig.navId){var object=document.getElementById("nav-"+pageConfig.navId);if(object)object.className+=" curr";}})();
</script>
<!-- header end -->


<script type="text/javascript">
    function submitForm(formName, actionName, dateSort) {
        $('#' + formName).attr('method', 'post');
        $('#' + formName).attr('action', actionName);
        $('#dateSort').val(dateSort);
        document.getElementById(formName).submit();
    }

    //用户点击下载后执行方法
    function sendMsg() {
        var ret = confirm('如您已安装京东LeBook客户端，请点击"确定"自动启动客户端\n如您尚未安装京东LeBook客户端，请点击"取消"将引导您免费安装客户端。');
        if (ret == true) {
            window.location = "LEBK://";
        } else if (confirm('如果您没有安装LeBook客户端，请点击"确定"按钮到京东网站下载\n如果您不需要安装，请点击"取消"按钮')) {
            window.open("https://e.jd.com/ebook/lebook_pc.aspx");
        }
        return;
    }
</script>

<div class="rel">
    <!--<div class="tag">
        <div class="new-app pressed">京东读书</div>
        <div class="old-app">京东阅读</div>
    </div> -->
    <div class="dushu">
        <img src="/pc-img/dushu.jpg">
      <div class="downLoad-btns">
	      <a class="new-ios" href="https://itunes.apple.com/cn/app/id1330602531?mt=8">
	      	<img src="/pc-img/ios.png"/>
	      </a>
	      <a class="new-android"  href="https://storage.jd.com/jdreader/jdread_guanwang_release.apk">
	      	<img src="/pc-img/android.png"/>
	      </a>
	      <a class="new-pc" href="https://storage.jd.com/jdreader/jdreadsetup.exe">
	      	<img src="/pc-img/pc.png"/>
	      </a>
	      <img class="erweima" src="/pc-img/erweima.png"/>
      </div>
    </div>
    <div class="yuedu" style="display: none">
        <img src="/pc-img/yuedu.jpg">
        <a class="old-ios" href="https://itunes.apple.com/cn/app/id506583396?mt=8"></a>
        <a class="old-android" href="http://a.app.qq.com/o/simple.jsp?pkgname=com.jingdong.app.reader&fromcase=40002&from=singlemessage&isappinstalled=0"></a>
        <div class="old-download">
            <div class="old-code">
                <img src="/pc-img/code.jpg">
            </div>
        </div>
        <a class="old-PC" href="https://storage.jd.com/jdtryread/JDReadForWin1.2.4.exe"></a>
    </div>
</div>
<script type="text/javascript">
    $(function(){
        $('.old-app').click(function(){
            $('.old-app').addClass('pressed');
            $('.new-app').removeClass('pressed');
            $('.dushu').fadeOut();
            $('.yuedu').fadeIn();
        });
        $('.new-app').click(function(){
            $('.new-app').addClass('pressed');
            $('.old-app').removeClass('pressed');
            $('.yuedu').fadeOut();
            $('.dushu').fadeIn();
        });
        $('.old-download').mouseover(function(){
            $('.old-code').fadeIn();
        });
        $('.old-download').mouseout(function(){
            $('.old-code').fadeOut();
        });
        $('.downLoad-btns a').mouseover(function(){
            //$(this).find('img').css('opacity','0.1')
            var downLoadImg = $(this).find('img')
            if (downLoadImg.prevObject[0].className === 'new-pc') {
              downLoadImg[0].src='/pc-img/pc-highlight.png'
              downLoadImg.css('opacity','1')
            } else if (downLoadImg.prevObject[0].className === 'new-android') {
              downLoadImg[0].src='/pc-img/android-highlight.png'
              downLoadImg.css('opacity','1')
            } else if (downLoadImg.prevObject[0].className === 'new-ios') {
              downLoadImg[0].src='/pc-img/ios-highlight.png'
              downLoadImg.css('opacity','1')
            } else {
              downLoadImg.css('opacity','0.1')
            }
	    })
	    $('.downLoad-btns a').mouseout(function(){
	        // $(this).find('img').css('opacity','1')
            var downLoadImg = $(this).find('img')
            if (downLoadImg.prevObject[0].className === 'new-pc') {
              downLoadImg[0].src='/pc-img/pc.png'
              downLoadImg.css('opacity','1')
            } else if (downLoadImg.prevObject[0].className === 'new-android') {
              downLoadImg[0].src='/pc-img/android.png'
              downLoadImg.css('opacity','1')
            } else if (downLoadImg.prevObject[0].className === 'new-ios') {
              downLoadImg[0].src='/pc-img/ios.png'
              downLoadImg.css('opacity','1')
            } else {
              downLoadImg.css('opacity','1')
            }
	    })
    });
    function getData(url, callback, params, other) {
        jQuery.ajax({
            type: 'get',
            url: url,
            dataType:"json",
            data: params,
            success:function(data){
                if (callback !== '' && typeof callback === 'function') {
                    callback(data, params, other);
                }
            },
            error: function(err) {
                console.log(err);
            }
        });
    }
    function setHref (data) {
        window.location.href = data.data.url;
    }
    var downUrl = 'https://jdread-api.jd.com/jdread/api/version';
    $('.new-android').click(function(){
        getData(downUrl, setHref);
    });

</script>
    <div class="w">
	<div id="service-2013">
		<dl class="fore1">
			<dt><b></b><strong>购物指南</strong></dt>
			<dd>
				<div><a href="//help.jd.com/help/question-56.html" target="_blank" rel="nofollow">购物流程</a></div>
				<div><a href="//help.jd.com/help/question-57.html" target="_blank" rel="nofollow">会员介绍</a></div>
				<div><a href="//help.jd.com/help/question-181.html" target="_blank" rel="nofollow">团购/机票</a></div>
				<div><a href="//help.jd.com/help/question-61.html" target="_blank" rel="nofollow">常见问题</a></div>
				<div><a href="//help.jd.com/help/question-63.html" target="_blank" rel="nofollow">大家电</a></div>
				<div><a href="//help.jd.com/index.html" target="_blank" rel="nofollow">联系客服</a></div>
			</dd>
		</dl>
		<dl class="fore2">
			<dt><b></b><strong>配送方式</strong></dt>
			<dd>
				<div><a href="//help.jd.com/help/question-64.html" target="_blank" rel="nofollow">上门自提</a></div>
				<div><a href="//help.jd.com/help/question-360.html" target="_blank" rel="nofollow">211限时达</a></div>
				<div><a href="//help.jd.com/help/question-65.html" target="_blank" rel="nofollow">快递运输</a></div>
				<div><a href="//market.jd.com/giftcard/index.html#one5" target="_blank" rel="nofollow">如何送礼</a></div>
				<div><a href="https://en.jd.com/" target="_blank">Global Shipping</a></div>
			</dd>
		</dl>
		<dl class="fore3">
			<dt><b></b><strong>支付方式</strong></dt>
			<dd>
				<div><a href="//help.jd.com/help/question-67.html" target="_blank" rel="nofollow">货到付款</a></div>
				<div><a href="//help.jd.com/help/question-68.html" target="_blank" rel="nofollow">在线支付</a></div>
				<div><a href="//help.jd.com/help/question-71.html" target="_blank" rel="nofollow">分期付款</a></div>
				<div><a href="//help.jd.com/help/question-69.html" target="_blank" rel="nofollow">邮局汇款</a></div>
				<div><a href="//help.jd.com/help/question-70.html" target="_blank" rel="nofollow">公司转账</a></div>
			</dd>
		</dl>
		<dl class="fore4">
			<dt><b></b><strong>售后服务</strong></dt>
			<dd>
				<div><a href="//help.jd.com/help/question-97.html" target="_blank" rel="nofollow">售后服务政策</a></div>
				<div><a href="//help.jd.com/help/question-98.html" target="_blank" rel="nofollow">售后服务流程</a></div>
				<div><a href="//help.jd.com/help/question-99.html" target="_blank" rel="nofollow">价格保护</a></div>
				<div><a href="//help.jd.com/help/question-100.html" target="_blank" rel="nofollow">退款说明</a></div>
				<div><a href="//myjd.jd.com/repair/repairs.action" target="_blank" rel="nofollow">返修/退换货</a></div>
				<div><a href="https://order.jd.com/center/list.action" target="_blank" rel="nofollow">取消订单</a></div>
			</dd>
		</dl>
		<dl class="fore5">
			<dt><b></b><strong>特色服务</strong></dt>
			<dd>
				<div><a href="//help.jd.com/help/question-79.html" target="_blank">夺宝岛</a></div>
				<div><a href="//help.jd.com/help/question-86.html" target="_blank">DIY装机</a></div>
				<div><a href="https://fuwu.jd.com/" target="_blank" rel="nofollow">延保服务</a></div>
				<div><a href="//market.jd.com/giftcard/index.html" target="_blank" rel="nofollow">京东礼品卡</a></div>
				<div><a href="//help.jd.com/help/question-91.html" target="_blank" rel="nofollow">节能补贴</a></div>
			</dd>
		</dl>
		<span class="clr"></span>
	</div>
</div><!-- service end -->    <div class="w">
	<div id="footer-2013">
		<div class="links">
			<a href="https://www.jd.com/intro/about.aspx" target="_blank" rel="nofollow">关于我们</a>|
			<a href="https://www.jd.com/contact/" target="_blank" rel="nofollow">联系我们</a>|
			<a href="https://zhaopin.jd.com" target="_blank" rel="nofollow">人才招聘</a>|
			<a href="https://www.jd.com/contact/joinin.aspx" target="_blank" rel="nofollow">商家入驻</a>|
			<a href="https://sale.jd.com/act/y3surX7qpM.html" target="_blank" rel="nofollow">广告服务</a>|
			<a href="https://app.jd.com/" target="_blank" rel="nofollow">手机京东</a>|
			<a href="https://club.jd.com/links.aspx" target="_blank">友情链接</a>|
			<a href="//cps.jd.com/" target="_blank">销售联盟</a>|
			<a target="_blank" href="https://club.jd.com/">京东社区</a>|
			<a target="_blank" href="https://gongyi.jd.com">京东公益</a></div>
		<div class="copyright">北京市公安局朝阳分局备案编号110105014669&nbsp;&nbsp;|&nbsp;&nbsp;京ICP证070359号&nbsp;&nbsp;|&nbsp;&nbsp;互联网药品信息服务资格证编号(京)-非经营性-2011-0034<br><a target="_blank" href="https://misc.360buyimg.com/skin/df/i/com/f_music.jpg" rel="nofollow">音像制品经营许可证苏宿批005号</a>&nbsp;&nbsp;|&nbsp;&nbsp;出版物经营许可证编号新出发(苏)批字第N-012号&nbsp;&nbsp;|&nbsp;&nbsp;互联网出版许可证编号新出网证(京)字150号<br><a target="_blank" href="https://misc.360buyimg.com/wz/wlwhjyxkz.jpg">网络文化经营许可证京网文[2011]0168-061号</a>&nbsp;&nbsp;Copyright&nbsp;&copy;&nbsp;2004-2013&nbsp;&nbsp;京东JD.com&nbsp;版权所有<br />京东旗下网站：<a href="https://channel.jd.com/luxury.html" target="_blank">360TOP</a>&nbsp;&nbsp;<a target="_blank" href="https://en.jd.com/">English Site</a></div>
		<div class="authentication">
			<a href="http://www.hd315.gov.cn/beian/view.asp?bianhao=010202007080200026" target="_blank" rel="nofollow">
				<img data-lazyload="https://img10.360buyimg.com/da/20110329/108_40_zZOKnl.gif" width="108" height="40" alt="经营性网站备案中心"></a>
			<script type="text/JavaScript">
				function CNNIC_change(eleId){
					var str= document.getElementById(eleId).href;
					var str1 =str.substring(0,(str.length-6));
					str1+=CNNIC_RndNum(6);
					document.getElementById(eleId).href=str1;
				}
				function CNNIC_RndNum(k){
					var rnd="";
					for (var i=0;i < k;i++)
						rnd+=Math.floor(Math.random()*10);
					return rnd;
				}</script>
			<a href="https://ss.cnnic.cn/verifyseal.dll?sn=2008070300100000031&ct=df&pa=294005" tabindex="-1" id="urlknet" target="_blank" rel="nofollow">
				<img alt="&#x53EF;&#x4FE1;&#x7F51;&#x7AD9;" name="CNNIC_seal" border="true"
					 data-lazyload="https://img11.360buyimg.com/da/g8/M03/0C/0E/rBEHaFCFC5QIAAAAAAASVQX9RAYAACb2wHUV1kAABJt760.gif"
					 width="108" height="40" oncontextmenu="return false;" onclick="CNNIC_change('urlknet')" /></a>
			<a href="http://about.58.com/fqz/index.html" target="_blank" rel="nofollow">
				<img data-lazyload="https://img12.360buyimg.com/da/g5/M02/0D/17/rBEIDE_nzcIIAAAAAAB30mYXo5QAACrhACj22IAAHfq378.png" width="108"
					 height="40" alt="朝阳网络警察"></a><a href="https://search.szfw.org/cert/l/CX20120111001803001836" target="_blank"
													 rel="nofollow">
			<img data-lazyload="https://img13.360buyimg.com/da/20120221/112_40_WvArIl.png" width="112" height="40"></a></div>
	</div>
</div><!-- footer end -->    <!--[if IE 6]>
<script type="text/javascript" src="https://misc.360buyimg.com/lib/js/2013/DD_belatedPNG.js"></script>
<script type="text/javascript">
(function(){
var A=(typeof _belatedPNG!="undefined")?_belatedPNG:[];
var B=[].concat(A).join(",");
DD_belatedPNG.fix(B);
})();
</script>
<![endif]-->
<script type="text/javascript" src="https://wl.jd.com/wl.js"></script>
<script type="text/javascript">
var _mvq = _mvq || [];
_mvq.push(['$setAccount', 'm-9-1']);
_mvq.push(['$logConversion']);
(function() {
    var mvl = document.createElement('script');
    mvl.type = 'text/javascript'; mvl.async = true;
    mvl.src = 'https://misc.360buyimg.com/lib/js/2012/mvl.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(mvl, s);
})();
</script></body>
</html>

<script type="text/javascript" src="https://wl.jd.com/wl.js"></script>
<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-2176661-1']);
    _gaq.push(['_setDomainName', 'jd.com']);
    _gaq.push(['_addOrganic', 'soso', 'w']);
    _gaq.push(['_addOrganic', 'sogou', 'query']);
    _gaq.push(['_addOrganic', 'youdao', 'q']);
    _gaq.push(['_addOrganic', 'baidu', 'word']);
    _gaq.push(['_addOrganic', 'baidu', 'q1']);
    _gaq.push(['_addOrganic', 'ucweb', 'keyword']);
    _gaq.push(['_addOrganic', 'ucweb', 'word']);
    _gaq.push(['_addOrganic', '114so', 'kw']);
    _gaq.push(['_trackPageview']);
    _gaq.push(['_trackPageLoadTime']);
    (function() {
        var ga = document.createElement('script');
        ga.type = 'text/javascript';
        ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
    })();

    jQuery(function(){
        jQuery.fn.UIDialog = function(options){
            var defaults = { IE :jQuery.browser.msie,
                IE6        :jQuery.browser.version == 6,
                FIREFOX    :jQuery.browser.mozilla,
                window     :$(window),
                document   :$(document),
                body       :$(document.body),
                id         :null,  // 需要赋值的ID
                callOnOpen :null,  // 弹出后调用
                callOnClose:null,  // 关闭后调用
                eventType  :null,  // 事件类型 click, blur, change, dblclick, error, focus, load, mousedown, mouseout, mouseup
                idContent  :null,  // 需要添加的id
                width      :'auto', // 宽
                height     :'auto', // 高
                title      :'温馨提示',// 标题
                content    :''// 内容
            };
            var opts = jQuery.extend({}, defaults, options);
            var instance = {
                // 初始化方法
                init: function(opts, me){
                    var that = this,
                            cache = jQuery.fn.UIDialog.cache;
                    for(var p in opts){ // opts 绑定到 instance
                        this[p] = opts[p];
                    }
                    that.me = me; // 被调用者
                    if("overdueTips" == opts.id){
                        that.createOverdueTips();
                    }
                    if("buyTips" == opts.id){
                        that.createBuyTips();
                    }
                    if("tips" == opts.id){
                        that.createDialog();
                    }
                    that.createMask();
                    that.mask.fadeTo('slow', 0.5).click(function(){
                        that.close();
                    });
                    cache.push(that.dialog);
                    cache.push(that.mask);
                    that.dialog.fadeIn('slow', function(){ that.callOnOpen && that.callOnOpen(); });
                    //that.setZIndex();
                },
                // 创建容器
                createDialog: function(){
                    var that = this,
                            dialog = $('<div class="ui-dialog"></div>').appendTo(this.body).hide(),
                            dialogTitle = $('<h1 class="ui-dialog-title"></h1>').appendTo(dialog),
                            dialogBody = $('<div class="ui-dialog-body" style="height: 148px; overflow: hidden;"></div>').appendTo(dialog),
                            bookLayer = $('<div class="bookLayer"></div>').appendTo(dialogBody),
                            p = $('<p></p>').appendTo(bookLayer),
                            divBtn = $('<div class="btn-wrap"><a href="https://sale.jd.com/act/W5hugLDc1R.html" class="red" target="_blank">立即安装</a></div>').appendTo(bookLayer),
                            a = $('<a href="javascript:;">已安装，启动应用</a>').appendTo(divBtn).click(function() {window.open("LEBK://Bought/")});
                    titleClose = $('<a class="ui-dialog-close" title="关闭"><span class="ui-icon ui-icon-delete"></span></a>').appendTo(dialog).click(function(){ that.close(); }),
                            cancelBtn = $('<a class="cancel-btn" href="javascript:;">取消下载</a>').appendTo(divBtn).click(function() {that.close();});
                    opts.id && dialog.attr('id', opts.id);
                    that.dialog = dialog;
                    that.title ? dialogTitle.append(that.title) : title.hide();
                    p.append(that.content);
                    that.IE6 && dialog.css({position:'absolute'});
                    that.setSize();
                    return that;
                },
                createBuyTips: function(){
                    var that = this,
                            dialog = $('<div class="ui-dialog"></div>').appendTo(this.body).hide(),
                            dialogTitle = $('<h1 class="ui-dialog-title"></h1>').appendTo(dialog),
                            dialogBody = $('<div class="ui-dialog-body" style="height: 148px; overflow: hidden;"></div>').appendTo(dialog),
                            bookLayer = $('<div class="bookLayer"></div>').appendTo(dialogBody),
                            p = $('<p></p>').appendTo(bookLayer),
                            divBtn = $('<div class="btn-wrap"><a href="https://sale.jd.com/act/MypqiIJPYx.html" class="red" style="width:200px;" target="_blank">立即购买畅读VIP服务</a></div>').appendTo(bookLayer),
                            titleClose = $('<a class="ui-dialog-close" title="关闭"><span class="ui-icon ui-icon-delete"></span></a>').appendTo(dialog).click(function(){ that.close(); });
                    opts.id && dialog.attr('id', opts.id);
                    that.dialog = dialog;
                    that.title ? dialogTitle.append(that.title) : title.hide();
                    p.append(that.content);
                    that.IE6 && dialog.css({position:'absolute'});
                    that.setSize();
                    return that;
                },
                createOverdueTips: function(){
                    var that = this,
                            dialog = $('<div class="ui-dialog"></div>').appendTo(this.body).hide(),
                            dialogTitle = $('<h1 class="ui-dialog-title"></h1>').appendTo(dialog),
                            dialogBody = $('<div class="ui-dialog-body" style="height: 148px; overflow: hidden;"></div>').appendTo(dialog),
                            bookLayer = $('<div class="bookLayer"></div>').appendTo(dialogBody),
                            p = $('<p></p>').appendTo(bookLayer),
                            divBtn = $('<div class="btn-wrap"></div>').appendTo(bookLayer),
                            btn = $('<a href="#" class="red" target="_blank">确认</a>').appendTo(divBtn).click(function(){ that.close(); }),
                            titleClose = $('<a class="ui-dialog-close" title="关闭"><span class="ui-icon ui-icon-delete"></span></a>').appendTo(dialog).click(function(){ that.close(); });
                    opts.id && dialog.attr('id', opts.id);
                    that.dialog = dialog;
                    that.title ? dialogTitle.append(that.title) : title.hide();
                    p.append(that.content);
                    that.IE6 && dialog.css({position:'absolute'});
                    that.setSize();
                    return that;
                },
                // 创建模板
                createMask: function(){
                    var that = this, body = that.body,
                            windowWidth = that.window.width(),
                            mask = $('<div class="ui-mask"></div>').appendTo(body).hide();
                    that.mask = mask;
                    mask.css({width: windowWidth, height: that.document.height()});
                    that.IE6 && mask.html('<iframe src="about:blank" style="width:100%;height:100%;position:absolute;top:0;left:0;z-index:-1;filter:alpha(opacity=0)"></iframe>'); // 添加全屏iframe以防止select穿透
                    return that;
                },
                // 设置大小
                setSize: function(){
                    var that = this,
                            dialog = that.dialog,
                            window = that.window,
                            windowWidth = window.width(),
                            windowHeight = window.height(),
                            left, top;
                    dialog.css({width: that.width, height: that.height});
                    var defaultTop = Math.floor((windowHeight - dialog.outerHeight()) / 2);
                    left = (windowWidth - dialog.width()) / 2 + 'px';
                    top = defaultTop + 'px';
                    dialog.css({left: left, top: top});
                    return that;
                },
                // 设置堆叠值
                /*  setZIndex: function(){
                      var that = this,
                              dialog = that.dialog,
                              mask = that.mask,
                              indexVal = jQuery.fn.UIDialog.globalIndex++; // 引用全局变量，否则每次初始化后值为原始值
                      dialog && dialog.css({zIndex: indexVal});
                      mask && mask.css({zIndex: indexVal - 1});
                      return that;
                  },*/
                // 关闭
                close: function(){
                    var that = this,
                            cache = jQuery.fn.UIDialog.cache,
                            dialog = cache[cache.length - 2],
                            mask = cache[cache.length - 1];
                    dialog.trigger('unload').unbind('click');
                    mask.trigger('unload').unbind('click');
                    that.slowRemove(dialog).slowRemove(mask);
                    cache.splice(cache.length - 2, 2);
                    return that;
                },
                // 渐隐
                slowRemove: function(ele){
                    var that = this;
                    ele.fadeOut('slow', function(){
                        that.callOnClose && that.callOnClose();
                        $(this).remove();
                    });
                    return that;
                }
            };
            var eventType = opts.eventType;
            if(eventType){ // 如果是 jQuery.fn.UIDialog 方式调用
                return this.each(function(index){
                    $(this).bind(eventType, function(){
                        instance.init(opts, $(this));
//                        return false;
                    });
                });
            } else { // 如果是 jQuery.UIDialog 方式调用
                instance.init(opts, $(this));
            }
        };
        // jQuery.fn.UIDialog.globalIndex = new Date().getFullYear() + '' + new Date().getHours();  // 全局堆叠值,不能超过最大值(2147483647)
        jQuery.fn.UIDialog.cache = []; // 缓存对象
    });
    function onlineRead(ebookId){
        jQuery.ajax({
            url : 'readbook/readbook_checkReadCard.action',
            data : {ebookId : ebookId},
            success : function(res) {
                if(res != -1 && res.code == 4){
                    jQuery.fn.UIDialog({
                        content: res.msg,
                        id: 'buyTips',
                        width: 442
                    });
                }
                if(res != -1 && (res.code == 5 || res.code == 1)){
                    jQuery.fn.UIDialog({
                        content: res.msg,
                        id: 'overdueTips',
                        width: 442
                    });
                }

                if(res != -1 && res.code == 0){
                    window.open("/read/startRead.action?bookId="+ebookId+"&readType=0");
                }
            }
        });
    }
    function pcRead(){
        jQuery.fn.UIDialog({
            content: "需要启动<strong> 京东阅读客户端 </strong>在线畅读",
            id: 'tips',
            width: 442
        });
    }

    function getRandomNum(Min,Max){
        var Range = Max - Min;
        var Rand = Math.random();
        return(Min + Math.round(Rand * Range));
    }
</script>

<!--这个脚本必须放在最底下-->
<script type="text/javascript" src="/js/2012_lib-v1.js"></script>
<script type="text/javascript" src="/js/myreadbooklist.js"></script>