<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-type" content="text/html; charset=gb2312" />
<title>最新滚动研究报告|研究评级|机构研报_新浪财经_新浪网</title>
<meta name="keywords" content="最新滚动研究报告,最新滚动机构研报" />
<meta name="description" content="新浪财经最新滚动行情中心,为您提供最新滚动研究报告,研究评级,机构研报信息查询." />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" / >
<script type="text/javascript" src="http://www.sinaimg.cn/jslib/jquery-1.4.2.min.js"></script>
<style type="text/css">
/* 初始化CSS */
html, body, ul, li, ol, dl, dd, dt, p, h1, h2, h3, h4, h5, h6, form, fieldset, legend,img{margin:0;padding:0;}
fieldset,img{border:none;}
address,caption,cite,code,dfn,th,var{font-style:normal;font-weight:normal;}
ul,ol{list-style:none;}
select,input{vertical-align:middle;}
select,input,textarea{font-size:12px;margin:0;}
table{border-collapse:collapse;}
body{background:#fff;color:#4e4e4e;padding:5px 0;font:12px/20px "宋体";}

.clearfix:after{content:".";display:block;height:0;visibility:hidden;clear:both;}
.clearfix{zoom:1;}
.clearit{clear:both;height:0;font-size:0;overflow:hidden;}

a{color:#009;text-decoration:none;}
a:visited{color:#800080;}
a:hover, a:active, a:focus{color:#f00;text-decoration:underline;}

a.linkRed:link,a.linkRed:visited{color:#f00!important;}/* 红色 */
a.linkRed:hover{color:#c00!important;}
a.linkRed01:link,a.linkRed01:visited{color:red!important}
a.linkRed01:hover{color:red!important}

/*自定义链接颜色*/
.fred { color:#f00 !important}
.fblack { color:#000 !important}
.fblue { color:#33F !important}
.forange { color:#F60 !important}
.fred:visited, .fblack:visited, .fblue:visited, .forange:visited{color:#800080 !important}
.fred:hover, .fblack:hover, .fblue:hover, .forange:hover{color:#f00 !important}

/*自定义标题链接颜色*/
.f_red, .f_red:visited, .f_red:hover { color:#f00 !important}
.f_black, .f_black:visited, .f_black:hover { color:#000 !important}
.f_blue, .f_blue:visited, .f_blue:hover { color:#18479B !important}
.f_orange, .f_orange:visited, .f_orange:hover { color:#F60 !important}

.space { height:10px; overflow:hidden; background:#fff; }
.isLine { text-decoration:underline !important; }
.f12 { font-size:12px !important}
.f14 { font-size:14px !important}
.f16 { font-size:16px !important}
.lh23 { line-height:23px !important }
.lh24 { line-height:24px !important }
.lh30 { line-height:30px !important }
.left{float:left}
.right{float:right}
.tal{text-align:left !important}
.tar{text-align:right !important}
.bold{ font-weight:bold;}
.nobottom{border-bottom:none !important}
.nobg{background:none !important}
h1, h2, h3, h4, h5, strong { font-weight:normal; }
.wrap { width:950px; margin:0 auto; }
/* 导航 */
.navTop {}
.navTop .nav01{background:url(/q/view/image/finance_zxh_0406_01.png) repeat-x; border:solid 1px #0988d2; line-height:33px; height:33px;}
.nav01 ul{height:25px; padding:4px 0}
.nav01 li{float:left; font-size:14px; padding:0 14px; height:25px; line-height:25px;}
.nav01 li.home{background:url(/q/view/image/finance_zxh_0406_01.png) no-repeat 0 -37px; width:130px; text-indent:-999em;overflow:hidden}
.nav01 li.current{ color:#fff79d; margin:0 14px; padding:0 9px; border:solid 1px #2aa6f1; background:url(/q/view/image/finance_zxh_0406_01.png) no-repeat 0 -77px; height:23px;}
.nav01 li.line{ border-left:solid 1px #0967bb; padding:0; margin-top:6px; border-right:solid 1px #9ad4f9; height:11px; width:0; overflow:hidden; font-size:0}
.nav02{ border:solid 1px #d8d8d8; background:#f3f3f3; line-height:20px; padding:5px 0 5px 18px; height:20px; font-family:Tahoma; vertical-align:middle}
.nav02 .radio{vertical-align: middle}
.navTop a:link, .navTop a:visited { color:#fff; display:block;}
.navTop a:hover { color:#fff;}
/* ============== 横切定义 ============== */
.main{border:solid 1px #d4dce7; margin-top:10px;}
/* ================== block define ================== */
/* 板块单独定义 */
.blk_01, .blk_01 form { vertical-align:middle}
.blk a:visited{ color:#800080;}
.blk a:hover{color:#c00;}
/* ================= commen define ================ */
/* 标题 */
.tb_01{}
.tb_01 th{background:#f6f9fa; border-bottom:solid 1px #d4dce7; line-height:28px; height:28px; text-align:center;}
.tb_01 td{ height:27px; line-height:27px; text-align:center; background:#fcfdfe}
.tb_01 td.f14{ padding-left:15px;}
.tb_01 .t01{ width:40px}
.tb_01 .t02{ padding-left:136px; text-align:left}
.tb_01 .t03{ width:110px}
.tb_01 .t04{ width:90px}
.tb_01 .t05{ width:144px;}
.tb_01 .fname05{ width:152px; height:20px; overflow:hidden}
.tb_01 .fname05 span{ display:block; width:800px; text-align:left; padding-left:10px;}
.tb_01 .t06{ width:74px; padding-left:10px; text-align:left}
.tb_01 .fname{ width:82px; height:20px; overflow:hidden}
.tb_01 .fname span{ display:block; width:800px; text-align:left; padding-left:10px;}
.tb_01 td.td10{ height:10px; overflow:hidden}
.tb_01 a:link{color:#18479b}
.tb_01 a:visited{color:#800080}
.tb_01 a:hover{ color:#0677d6;}
/* 分页 */
.page{background:url(/q/view/image/finance_zxh_0406_02.png) repeat-x; padding:20px 0; margin:20px;}
.pagebox{overflow:hidden; zoom:1; font-size:12px; font-family:"宋体",sans-serif;}
.pagebox span{float:left; margin-right:2px; overflow:hidden; text-align:center; background:#fff;}
.pagebox span a{display:block; overflow:hidden; zoom:1; _float:left;}
.pagebox span.pagebox_pre_nolink{border:1px #ddd solid; width:53px; height:21px; line-height:21px; text-align:center; color:#999; cursor:default;}
.pagebox span.pagebox_pre{color:#3568b9; height:23px;}
.pagebox span.pagebox_pre a,.pagebox span.pagebox_pre a:visited,.pagebox span.pagebox_next a,.pagebox span.pagebox_next a:visited{border:1px #c2c1c1 solid; background:#f5f4f4; color:#18479b; text-decoration:none; text-align:center; width:53px; cursor:pointer; height:21px; line-height:21px;}
.pagebox span.pagebox_pre a:hover,.pagebox span.pagebox_pre a:active,.pagebox span.pagebox_next a:hover,.pagebox span.pagebox_next a:active{color:#363636; border:1px #2e6ab1 solid;}
.pagebox span.pagebox_num_nonce{padding:0 8px; height:23px; line-height:23px; color:#fff; cursor:default; background:#09a9ec; font-weight:bold;}
.pagebox span.pagebox_num{color:#3568b9; height:23px;}
.pagebox span.pagebox_num a,.pagebox span.pagebox_num a:visited{border:1px #c2c1c1 solid; color:#18479b; background:#f5f4f4; text-decoration:none; padding:0 8px; cursor:pointer; height:21px; line-height:21px;}
.pagebox span.pagebox_num a:hover,.pagebox span.pagebox_num a:active{border:1px #2e6ab1 solid;color:#363636;}
.pagebox span.pagebox_num_ellipsis{color:#393733; width:22px; background:none; line-height:23px;}
.pagebox span.pagebox_next_nolink{border:1px #ddd solid; width:53px; height:21px; line-height:21px; text-align:center; color:#999; cursor:default;}
</style>
<script type="text/javascript">
        function url_set_search(key,value,clear){
            var search = window.location.search;
            var pathname = window.location.pathname;
            var keyValue = new Array();
            if(search && search.charAt(0) == '?'){
                search = search.substr(1);
            }
            var flag = false;
            if(search && !clear){
                var arr = search.split('&');
                for(var i =0;i<arr.length;i++){
                    var tmp = arr[i].split('=');
                    if(tmp[0]==key){
                        if(value){
                            keyValue.push(key+"="+encodeURIComponent(value));
                        }
                        flag = true;
                    }
                    else{
                        keyValue.push(arr[i]);
                    }
                }
            }
            if(flag == false){
                keyValue.push(key+"="+encodeURIComponent(value));
            }
            search = keyValue.join("&");
            search = search?"?"+search:"";
            window.open(pathname+search,'_self');

            if(event){
                if (event.stopPropagation)
                event.stopPropagation();
                if (event.preventDefault)
                event.preventDefault();
                event.cancelBubble = true;
                event.returnValue = false;
            }
            return false;
        }
        function set_page_num(number){
            url_set_search('p',number,false);
        }
</script>
</head>
<body>
<div class="wrap">
  <!-- 标准二级导航_财经 begin -->
  <style type="text/css">
.secondaryHeader{height:33px;overflow:hidden;background:url(http://i2.sinaimg.cn/dy/images/header/2008/standardl2nav_bg.gif) repeat-x #fff;color:#000;font-size:12px;font-weight:100;}
.secondaryHeader a,.secondaryHeader a:visited{color:#000;text-decoration:none;}
.secondaryHeader a:hover,.secondaryHeader a:active{color:#c00;text-decoration:underline;}
.sHBorder{border:1px #e3e3e3 solid;padding:0 10px 0 12px;overflow:hidden;zoom:1;}
.sHLogo{float:left;height:31px;line-height:31px;overflow:hidden;}
.sHLogo span,.sHLogo span a,.sHLogo span a:link,.sHLogo span a:visited,.sHLogo span a:hover{display:block;*float:left;display:table-cell;vertical-align:middle;*display:block;*font-size:27px;*font-family:Arial;height:31px;}
.sHLogo span,.sHLogo span a img,.sHLogo span a:link img,.sHLogo span a:visited img,.sHLogo span a:hover img{vertical-align:middle;}
.sHLinks{float:right;line-height:31px;}
</style>
  <script type="text/javascript" src="http://finance.sina.com.cn/stock/reaserchyjbg/report/report_industry.js"></script>
<script type="text/javascript" src="http://finance.sina.com.cn/stock/reaserchyjbg/report/report_orgname.js"></script>
<script type="text/javascript" src="http://www.sinaimg.cn/cj/financewidget/js/Calendar_1.0.1.js"></script>
<div class="secondaryHeader">
    <div class="sHBorder">
      <div class="sHLogo"><span><a href="http://finance.sina.com.cn/"><img src="http://i1.sinaimg.cn/dy/images/header/2009/standardl2nav_sina_new.gif" alt="新浪网" /></a><a href="http://finance.sina.com.cn/"><img src="http://i1.sinaimg.cn/dy/images/header/2009/standardl2nav_finance.gif" alt="新浪财经" /></a></span></div>
      <div class="sHLinks"><a href="http://finance.sina.com.cn/">财经首页</a>&nbsp;|&nbsp;<a href="http://www.sina.com.cn/">新浪首页</a>&nbsp;|&nbsp;<a href="http://news.sina.com.cn/guide/">新浪导航</a></div>
    </div>
  </div>
  <!-- 标准二级导航_财经 end -->
  <!-- 导航 begin -->
  <div class="navTop">
    <div class="nav01">
      <ul>
        <li class="home">
            <a href="http://finance.sina.com.cn/stock/report/index.shtml">研究报告</a>
        </li>
        <li class="current">最新滚动</li>        <li class="line"></li>
        <li>
            <a href="http://roll.finance.sina.com.cn/finance/zq1/zldx/index.shtml">主力动向</a>
        </li>
        <li class="line"></li>
        <li>
            <a href="http://vip.stock.finance.sina.com.cn/q/go.php/vIR_RatingNewest/index.phtml">个股评级</a>
        </li>
        <li class="line"></li>
        <li><a href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/company/index.phtml">公司研究</a></li>        <li class="line"></li>
        <li><a href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/industry/index.phtml">行业研究</a></li>        <li class="line"></li>
        <li><a href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/strategy/index.phtml">投资策略</a></li>        <li class="line"></li>
        <li><a href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/macro/index.phtml">宏观研究</a></li>        <li class="line"></li>
        <li>
            <a href="http://vip.stock.finance.sina.com.cn/q/go.php/vInvestConsult/kind/qgqp/index.phtml">个股点评</a>
        </li>
      </ul>
    </div>
        <script type="text/javascript" src="http://www.sinaimg.cn/cj/financewidget/js/SuggestServer_3_0_19.js"></script>
    <script type="text/javascript">(new SuggestServer()).bind({"input": "key", "value": "@3@", "type": "stock", "width": 180, "target":"_self","link": "/q/go.php/vIR_StockSearch/key/@2@.phtml"});</script>
    <script type="text/javascript">    jQuery.noConflict();</script>
    <script type="text/javascript">
        var _industry = '';
        var _orgname = '';
        var searchType = 'title';
        function checkForm()
        {
            if(searchType == 'stock'){
                var symbol = jQuery.trim(jQuery('#symbol').val());
                if(symbol == '')
                    return false;
                else{
                    var pattern = /^(sh|sz)?[0-9]{6}$/;
                    var rs = pattern.test(symbol);
                    if(rs == false){
                        alert('不正确的股票代码');
                        return false;
                    }
                }
            }else if(jQuery.trim(jQuery('#'+searchType).val()) == '')
                return false;
            return true;
        }
        function search(t)
        {
            searchType = t;
            switch(t)
            {
                case 'stock':
                    jQuery('#symbol').show();
					jQuery('#pubdate').hide();
                    jQuery('#searchInner').html('');
                    break;
				case 'pubdate':
					jQuery('#symbol').hide();
					jQuery('#pubdate').show();
                    jQuery('#searchInner').html('');
					break;
                case 'analysts':
                case 'title':
                    var c = '<input name="'+t+'" id="'+t+'" type="text" size="20">';
                    jQuery('#searchInner').html(c);
                    jQuery('#symbol').hide();
					jQuery('#pubdate').hide();
                    break;
                case 'orgname':
                    if(_orgname == '')
                    {
                        var _listWithoutID = ['reportOrgname'];
                        var _list;
                        for(var i = 0;i < _listWithoutID.length;i++)
                        {
                            _list = window[_listWithoutID[i]] || [];
                            _orgname = jQuery('<select name="orgname" id="orgname">');
                            for(var j = 0;j < _list.length;j++)
                            {
                                _orgname.append(jQuery('<option value="'+_list[j].svalue + '">').html(_list[j].svalue));
                            }
                        }
                    }
                    jQuery('#searchInner').html(_orgname);
                    jQuery('#symbol').hide();
					jQuery('#pubdate').hide();
                    break;
                case 'industry':
                    if(_industry == '')
                    {
                        var _listWithoutID = ['reportIndustry'];
                        var _list;
                        for(var i = 0;i < _listWithoutID.length;i++)
                        {
                            _list = window[_listWithoutID[i]] || [];
                            _industry = jQuery('<select name="industry" id="industry">');
                            for(var j = 0;j < _list.length;j++)
                            {
                                _industry.append(jQuery('<option value="'+_list[j].svalue + '">').html(_list[j].svalue));
                            }
                        }
                    }
                    jQuery('#searchInner').html(_industry);
                    jQuery('#symbol').hide();
					jQuery('#pubdate').hide();
                    break;
                default:
                    break;
            }
        }
        jQuery(document).ready(function(){
			jQuery('#pubdate').hide();
            var t1 = '';
            if(t1 != '' && t1 != 'all')
            {
                jQuery('#t1_'+t1).click();
                if(t1 == '1'){
                    jQuery('#orgname').val('');
                }else if(t1 == '2'){
                    jQuery('#symbol').val('');
                }else if(t1 == '3'){
                    jQuery('#industry').val('');
                }else if(t1 == '4'){
                    jQuery('#analysts').val('');
                }else if(t1 == '5'){
                    jQuery('#title').val('');
                }else if(t1 == '6'){
                    jQuery('#pubdate').val('');
                }
            }
            else
            {
                jQuery('#t1_6').click();
            }
        })
    </script>
    <div class="nav02">
        <div class="blk_01">
        <form method="get" action="/q/go.php/vReport_List/kind/search/index.phtml" onsubmit="return checkForm()" style="position:relative;">
            <span class="f_blue">研报搜索：</span>
            <input type="radio" name="t1" class="radio" id="t1_1" value="1" onclick="search('orgname')" /> 研究机构
            <input type="radio" name="t1" class="radio" id="t1_2" value="2" onclick="search('stock')" /> 公司股票
            <input type="radio" name="t1" class="radio" id="t1_3" value="3" onclick="search('industry')" /> 行业分类
            <input type="radio" name="t1" class="radio" id="t1_4" value="4" onclick="search('analysts')" /> 分析师
            <input type="radio" name="t1" class="radio" id="t1_5" value="5" onclick="search('title')"/> 标题
			<input type="radio" name="t1" class="radio" id="t1_6" value="6" onclick="search('pubdate')"/> 发布日期
            <span id="searchInner">
                <!--input name="title" id="title" type="text" size="20"-->
            </span>
            <input name="symbol" id="symbol" type="text" size="20" style="display:none" />
			<input name="pubdate" id="pubdate" type="text" size="20" value="2019-10-05" />
            <input type="submit" value="搜索" class="search_btn" />
            <script type="text/javascript">
				(new SuggestServer()).bind({"input": "symbol", "value": "@3@", "type": "stock", "width": 180});
				var calendar = new Calendar("pubdate", false, false, [155, 800, 0.95, "solid", "#EEE", "#FFF", 3, 3, 0.2, "#000", "#444", "#F6F8FD", "#333", "#F1F5FC", "#000", "#EFF3FB", false, false]);
			</script>
        </form>
        </div>
    </div>
</div>
  <!-- 导航 end -->

  <!-- main -->
  <div class="main">
   <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tb_01">
  <tr>
    <th scope="col" class="t01">序号</th>
    <th scope="col" class="t02">标题</th>
    <th scope="col" class="t03">报告类型</th>
    <th scope="col" class="t04">发布日期</th>
    <th scope="col" class="t05">机构</th>
    <th scope="col" class="t06">研究员</th>
  </tr>
  <tr>
    <td colspan="6" class="td10"></td>
  </tr>
            <tr>
            <td>1</td>
            <td class="tal f14">
                <a target="_blank" title="天风总量联席解读:能否持仓过节?" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724411/index.phtml">
                    天风总量联席解读:能否持仓过节?                </a>
            </td>
            <td>投资策略</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%CC%EC%B7%E7%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>天风证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>天风证券研究所</span></div></td>
     </tr>
           <tr>
            <td>2</td>
            <td class="tal f14">
                <a target="_blank" title="大类资产市场变点检测周报(2019年9月第5周):弹劾门一波三折,金价重回千五以下" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724409/index.phtml">
                    大类资产市场变点检测周报(2019年9月第5周):弹劾门一波...                </a>
            </td>
            <td>投资策略</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%D6%D0%D0%C5%BD%A8%CD%B6%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>中信建投证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>丁鲁明,王赟杰</span></div></td>
     </tr>
           <tr>
            <td>3</td>
            <td class="tal f14">
                <a target="_blank" title="中国建设银行贵金属市场" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724407/index.phtml">
                    中国建设银行贵金属市场                </a>
            </td>
            <td>投资策略</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%D6%D0%B9%FA%BD%A8%C9%E8%D2%F8%D0%D0%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>中国建设银行股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>建设银行研究所</span></div></td>
     </tr>
           <tr>
            <td>4</td>
            <td class="tal f14">
                <a target="_blank" title="FOF组合推荐周报:上周规模低估FOF组合表现优异" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724405/index.phtml">
                    FOF组合推荐周报:上周规模低估FOF组合表现优异                </a>
            </td>
            <td>投资策略</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%CC%EC%B7%E7%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>天风证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>吴先兴</span></div></td>
     </tr>
           <tr>
            <td>5</td>
            <td class="tal f14">
                <a target="_blank" title="贵金属日报:关注头肩顶是否成立" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724403/index.phtml">
                    贵金属日报:关注头肩顶是否成立                </a>
            </td>
            <td>投资策略</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%D0%CB%D2%B5%BE%AD%BC%C3%D1%D0%BE%BF%D7%C9%D1%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>兴业经济研究咨询股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>兴业研究所</span></div></td>
     </tr>
           <tr>
            <td>6</td>
            <td class="tal f14">
                <a target="_blank" title="固收专题分析报告:城投非标手册~华东篇下(2019版)" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724401/index.phtml">
                    固收专题分析报告:城投非标手册~华东篇下(2019版)                </a>
            </td>
            <td>投资策略</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%FA%BD%F0%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>国金证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>周岳</span></div></td>
     </tr>
           <tr>
            <td>7</td>
            <td class="tal f14">
                <a target="_blank" title="东方量化策略周报" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724399/index.phtml">
                    东方量化策略周报                </a>
            </td>
            <td>投资策略</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B6%AB%B7%BD%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>东方证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>朱剑涛</span></div></td>
     </tr>
           <tr>
            <td>8</td>
            <td class="tal f14">
                <a target="_blank" title="汽车整车行业:贵阳全面取消汽车限购,地方积极响应国家促消费政策" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724397/index.phtml">
                    汽车整车行业:贵阳全面取消汽车限购,地方积极响应国家促消费政策                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%D6%D0%D0%C5%BD%A8%CD%B6%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>中信建投证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>余海坤,陶亦然</span></div></td>
     </tr>
           <tr>
            <td>9</td>
            <td class="tal f14">
                <a target="_blank" title="A股市场投资策略周报:节前效应逐渐释放,夯实市场多头力量" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724395/index.phtml">
                    A股市场投资策略周报:节前效应逐渐释放,夯实市场多头力量                </a>
            </td>
            <td>投资策略</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B2%B3%BA%A3%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>渤海证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>宋亦威</span></div></td>
     </tr>
           <tr>
            <td>10</td>
            <td class="tal f14">
                <a target="_blank" title="电子行业周报:贸易战波折不改行业复苏核心逻辑,继续看好5G产业趋势" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724387/index.phtml">
                    电子行业周报:贸易战波折不改行业复苏核心逻辑,继续看好5G产...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BB%AA%B4%B4%D6%A4%C8%AF%D3%D0%CF%DE%D4%F0%C8%CE%B9%AB%CB%BE">
                    <div class="fname05"><span>华创证券有限责任公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>耿琛,蒋高振</span></div></td>
     </tr>
           <tr>
            <td>11</td>
            <td class="tal f14">
                <a target="_blank" title="食品饮料行业周报:原奶涨价推动牧场盈利改善,竞争加剧压制液奶龙头业绩" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724385/index.phtml">
                    食品饮料行业周报:原奶涨价推动牧场盈利改善,竞争加剧压制液奶...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%C6%BD%B0%B2%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>平安证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>文献,刘彪</span></div></td>
     </tr>
           <tr>
            <td>12</td>
            <td class="tal f14">
                <a target="_blank" title="化工行业2019年前三季度运行前瞻:整体下行,偶有亮色" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724383/index.phtml">
                    化工行业2019年前三季度运行前瞻:整体下行,偶有亮色                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B3%A4%BD%AD%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>长江证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>马太,谢楠</span></div></td>
     </tr>
           <tr>
            <td>13</td>
            <td class="tal f14">
                <a target="_blank" title="银行行业周报:银行中报利润增速6.75%;同业业务监管面临强化" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724381/index.phtml">
                    银行行业周报:银行中报利润增速6.75%;同业业务监管面临强化                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%C6%BD%B0%B2%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>平安证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>陈骁</span></div></td>
     </tr>
           <tr>
            <td>14</td>
            <td class="tal f14">
                <a target="_blank" title="银行业:同业存单周报" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724379/index.phtml">
                    银行业:同业存单周报                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%D0%CB%D2%B5%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>兴业证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>傅慧芳,陈绍兴</span></div></td>
     </tr>
           <tr>
            <td>15</td>
            <td class="tal f14">
                <a target="_blank" title="家用电器2019W34周观点:格力降价带动销售,关注新冷年开盘" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724377/index.phtml">
                    家用电器2019W34周观点:格力降价带动销售,关注新冷年开盘                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%CC%EC%B7%E7%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>天风证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>蔡雯娟</span></div></td>
     </tr>
           <tr>
            <td>16</td>
            <td class="tal f14">
                <a target="_blank" title="东吴证券食品饮料行业8月阿里系线上数据点评" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724375/index.phtml">
                    东吴证券食品饮料行业8月阿里系线上数据点评                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B6%AB%CE%E2%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>东吴证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>马莉,杨默曦</span></div></td>
     </tr>
           <tr>
            <td>17</td>
            <td class="tal f14">
                <a target="_blank" title="医药与健康护理行业信息点评:NSCLC指导原则发布,规范临床终点获益标准" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724373/index.phtml">
                    医药与健康护理行业信息点评:NSCLC指导原则发布,规范临床...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BA%A3%CD%A8%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>海通证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>余文心</span></div></td>
     </tr>
           <tr>
            <td>18</td>
            <td class="tal f14">
                <a target="_blank" title="新材料行业周报:关注电子新材料及金银比修复机会" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724371/index.phtml">
                    新材料行业周报:关注电子新材料及金银比修复机会                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%FA%B6%BC%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>国都证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>王树宝</span></div></td>
     </tr>
           <tr>
            <td>19</td>
            <td class="tal f14">
                <a target="_blank" title="房地产行业:本周商品房成交量环比回暖,土地市场持续走弱" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724369/index.phtml">
                    房地产行业:本周商品房成交量环比回暖,土地市场持续走弱                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BA%A3%CD%A8%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>海通证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>涂力磊,杨凡</span></div></td>
     </tr>
           <tr>
            <td>20</td>
            <td class="tal f14">
                <a target="_blank" title="贝斯美:新股询价报告" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724367/index.phtml">
                    贝斯美:新股询价报告                </a>
            </td>
            <td>公司研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BB%AA%F6%CE%D6%A4%C8%AF%D3%D0%CF%DE%D4%F0%C8%CE%B9%AB%CB%BE">
                    <div class="fname05"><span>华鑫证券有限责任公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>于芳</span></div></td>
     </tr>
           <tr>
            <td>21</td>
            <td class="tal f14">
                <a target="_blank" title="手机射频行业深度报告:5G已至,射频前端先行" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724365/index.phtml">
                    手机射频行业深度报告:5G已至,射频前端先行                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%C6%BD%B0%B2%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>平安证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>刘舜逢</span></div></td>
     </tr>
           <tr>
            <td>22</td>
            <td class="tal f14">
                <a target="_blank" title="银行业研究周报:创设标准化票据加大对中小银行流动性支持" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724357/index.phtml">
                    银行业研究周报:创设标准化票据加大对中小银行流动性支持                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%CC%EC%B7%E7%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>天风证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>廖志明,朱于畋</span></div></td>
     </tr>
           <tr>
            <td>23</td>
            <td class="tal f14">
                <a target="_blank" title="电气设备行业周报:风光持续向好,新能源车底部掘金" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724344/index.phtml">
                    电气设备行业周报:风光持续向好,新能源车底部掘金                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%CC%AB%C6%BD%D1%F3%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>太平洋证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>张文臣,刘晶敏,周涛,方杰</span></div></td>
     </tr>
           <tr>
            <td>24</td>
            <td class="tal f14">
                <a target="_blank" title="金融行业周报:短期贝塔属性占主导,建议逢低配置" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724338/index.phtml">
                    金融行业周报:短期贝塔属性占主导,建议逢低配置                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%CC%AB%C6%BD%D1%F3%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>太平洋证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>罗惠洲,刘涛</span></div></td>
     </tr>
           <tr>
            <td>25</td>
            <td class="tal f14">
                <a target="_blank" title="中国宏观观察:QFII/RQFII总额度取消加速中国市场对外开放" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724336/index.phtml">
                    中国宏观观察:QFII/RQFII总额度取消加速中国市场对外开放                </a>
            </td>
            <td>宏观经济</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BD%BB%D2%F8%B9%FA%BC%CA%D6%A4%C8%AF%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>交银国际证券有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>交银国际证券研究所</span></div></td>
     </tr>
           <tr>
            <td>26</td>
            <td class="tal f14">
                <a target="_blank" title="策略报告:19年前三季度盘点,港股、科创板共11家无利润生物医药公司申报,有何特点" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724334/index.phtml">
                    策略报告:19年前三季度盘点,港股、科创板共11家无利润生物...                </a>
            </td>
            <td>投资策略</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B0%B2%D0%C5%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>安信证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>诸海滨</span></div></td>
     </tr>
           <tr>
            <td>27</td>
            <td class="tal f14">
                <a target="_blank" title="顺网科技:网吧或将成为桌面云的绝佳应用场景" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724332/index.phtml">
                    顺网科技:网吧或将成为桌面云的绝佳应用场景                </a>
            </td>
            <td>公司研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%FA%CC%A9%BE%FD%B0%B2%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>国泰君安证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>李沐华</span></div></td>
     </tr>
           <tr>
            <td>28</td>
            <td class="tal f14">
                <a target="_blank" title="万达信息:人寿领导下公司进入发展新阶段" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724328/index.phtml">
                    万达信息:人寿领导下公司进入发展新阶段                </a>
            </td>
            <td>公司研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%FA%CC%A9%BE%FD%B0%B2%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>国泰君安证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>李沐华</span></div></td>
     </tr>
           <tr>
            <td>29</td>
            <td class="tal f14">
                <a target="_blank" title="淳中科技重大事项点评:拟募集3亿转债研发芯片,有望充分受益国产替代" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724326/index.phtml">
                    淳中科技重大事项点评:拟募集3亿转债研发芯片,有望充分受益国...                </a>
            </td>
            <td>公司研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BB%AA%B4%B4%D6%A4%C8%AF%D3%D0%CF%DE%D4%F0%C8%CE%B9%AB%CB%BE">
                    <div class="fname05"><span>华创证券有限责任公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>陈宝健,邓芳程</span></div></td>
     </tr>
           <tr>
            <td>30</td>
            <td class="tal f14">
                <a target="_blank" title="汇顶科技:屏下指纹持续高增长,平台型企业迎接IOT大时代" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724323/index.phtml">
                    汇顶科技:屏下指纹持续高增长,平台型企业迎接IOT大时代                </a>
            </td>
            <td>公司研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%E2%B4%F3%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>光大证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>刘凯</span></div></td>
     </tr>
           <tr>
            <td>31</td>
            <td class="tal f14">
                <a target="_blank" title="汇川技术:Q2业绩降幅环比收窄,电梯及轨交业务提供有力支撑" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724320/index.phtml">
                    汇川技术:Q2业绩降幅环比收窄,电梯及轨交业务提供有力支撑                </a>
            </td>
            <td>公司研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%CC%AB%C6%BD%D1%F3%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>太平洋证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>张文臣,周涛,刘晶敏,方杰</span></div></td>
     </tr>
           <tr>
            <td>32</td>
            <td class="tal f14">
                <a target="_blank" title="信维通信深度报告:国内泛射频龙头企业,长期成长动能充足" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724318/index.phtml">
                    信维通信深度报告:国内泛射频龙头企业,长期成长动能充足                </a>
            </td>
            <td>公司研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B6%AB%DD%B8%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>东莞证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>魏红梅</span></div></td>
     </tr>
           <tr>
            <td>33</td>
            <td class="tal f14">
                <a target="_blank" title="宏观周报:兼论宽松货币的约束及其影响!没有水牛快牛,只有业绩慢牛" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724316/index.phtml">
                    宏观周报:兼论宽松货币的约束及其影响!没有水牛快牛,只有业绩...                </a>
            </td>
            <td>宏观经济</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BA%A3%CD%A8%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>海通证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>姜超,李金柳,于博,宋潇</span></div></td>
     </tr>
           <tr>
            <td>34</td>
            <td class="tal f14">
                <a target="_blank" title="环旭电子:三季度有望显著回暖,后续增长点明确" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724314/index.phtml">
                    环旭电子:三季度有望显著回暖,后续增长点明确                </a>
            </td>
            <td>公司研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%FA%CC%A9%BE%FD%B0%B2%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>国泰君安证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>陈飞达,王聪</span></div></td>
     </tr>
           <tr>
            <td>35</td>
            <td class="tal f14">
                <a target="_blank" title="星网锐捷公司跟踪报告:云桌面行业龙头,发力安可成长再添动能" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724308/index.phtml">
                    星网锐捷公司跟踪报告:云桌面行业龙头,发力安可成长再添动能                </a>
            </td>
            <td>公司研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BA%A3%CD%A8%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>海通证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>余伟民,朱劲松</span></div></td>
     </tr>
           <tr>
            <td>36</td>
            <td class="tal f14">
                <a target="_blank" title="公用事业行业周报:电价新政,长期估值提升将大超短期盈利下降" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724280/index.phtml">
                    公用事业行业周报:电价新政,长期估值提升将大超短期盈利下降                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BA%A3%CD%A8%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>海通证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>吴杰,张磊,戴元灿</span></div></td>
     </tr>
           <tr>
            <td>37</td>
            <td class="tal f14">
                <a target="_blank" title="医药与健康护理行业周报:集采扩围结果出炉,行业分化加大,对医药板块影响有限" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724278/index.phtml">
                    医药与健康护理行业周报:集采扩围结果出炉,行业分化加大,对医...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BA%A3%CD%A8%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>海通证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>余文心</span></div></td>
     </tr>
           <tr>
            <td>38</td>
            <td class="tal f14">
                <a target="_blank" title="计算机行业网络安全深度:市场更大,景气更高" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724264/index.phtml">
                    计算机行业网络安全深度:市场更大,景气更高                </a>
            </td>
            <td>行业研究</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%D0%CB%D2%B5%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>兴业证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>蒋佳霖</span></div></td>
     </tr>
           <tr>
            <td>39</td>
            <td class="tal f14">
                <a target="_blank" title="宏观事件点评:2019年9月制造业及非制造业PMI数据点评,弱势回升,三季度经济下行压力仍较大" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724252/index.phtml">
                    宏观事件点评:2019年9月制造业及非制造业PMI数据点评,...                </a>
            </td>
            <td>宏观经济</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BB%AA%C1%FA%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>华龙证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>华龙证券研究所</span></div></td>
     </tr>
           <tr>
            <td>40</td>
            <td class="tal f14">
                <a target="_blank" title="港股点评:恒指跌87点,金融股弱,沪指微升3点,道指跌70点" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4724250/index.phtml">
                    港股点评:恒指跌87点,金融股弱,沪指微升3点,道指跌70点                </a>
            </td>
            <td>投资策略</td>
            <td>2019-09-30</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B1%A6%CD%A8%D6%A4%C8%AF%28%D1%C7%D6%DE%29%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>宝通证券(亚洲)有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>宝通证券研究所</span></div></td>
     </tr>
   </table>
<!-- 分页 begin -->
<div class="page">
<table cellspacing="0" style="margin:0 auto;"><tr><td>
<div class="pagebox" id="_function_code_page">
     <span class='pagebox_pre_nolink'>首页</span>  <span class='pagebox_pre_nolink'>上一页</span>  <span class='pagebox_num_nonce'>1</span>  <span class='pagebox_num'><a href="javascript:void(0)" onclick="set_page_num('2')">2</a></span>  <span class='pagebox_num'><a href="javascript:void(0)" onclick="set_page_num('3')">3</a></span>  <span class='pagebox_num'><a href="javascript:void(0)" onclick="set_page_num('4')">4</a></span>  <span class='pagebox_num'><a href="javascript:void(0)" onclick="set_page_num('5')">5</a></span>  <span class='pagebox_num'><a href="javascript:void(0)" onclick="set_page_num('6')">6</a></span>  <span class='pagebox_next'><a href="javascript:void(0)" onclick="set_page_num('2')">下一页</a></span>  <span class='pagebox_next'><a href="javascript:void(0)" onclick="set_page_num('7465')">最末页</a></span> </div>
</td></tr></table>
</div>
<!-- 分页 end -->
  </div>
<!-- end main -->
<!-- footer -->

<style type="text/css">
#footer{width:950px; text-align:center; line-height:21px; font-size:12px;margin-top:20px;color:#333;margin-left:auto;margin-right:auto;}
#footer a:link{color:#000099}
#footer a:visited{color:#800080}
#footer a:hover{color:#ff0000;text-decoration:underline;}
#footer a:active {color:#0100A3; text-decoration:none;}
</style>
<!-- SUDA_CODE_START --> 
<script type="text/javascript" src="//www.sinaimg.cn/unipro/pub/suda_s_v851c.js"></script>
<script type="text/javascript" > 
_S_pSt(_S_PID_); 
</script>
<!-- SUDA_CODE_END -->

<div id="footer">
客户服务热线：4000520066　　
欢迎批评指正<br>

<a target="_blank" href="http://tech.sina.com.cn/focus/sinahelp.shtml">常见问题解答</a>  
<a target="_blank" href="http://net.china.cn/chinese/index.htm">互联网违法和不良信息举报</a>　
<a target="_blank" href="https://gu.sina.cn/pc/feedback/">新浪财经意见反馈留言板</a>
<br><br>
<a href="http://corp.sina.com.cn/chn/">新浪简介</a> | <a href="http://corp.sina.com.cn/eng/">About Sina</a> | <a href="http://emarketing.sina.com.cn/">广告服务</a> | <a href="http://www.sina.com.cn/contactus.html">联系我们</a> | <a href="http://corp.sina.com.cn/chn/sina_job.html">招聘信息</a> | <a href="http://www.sina.com.cn/intro/lawfirm.shtml">网站律师</a> | <a href="http://english.sina.com">SINA English</a> | <a href="http://members.sina.com.cn/apply/">通行证注册</a> | <a href="http://help.sina.com.cn/">产品答疑</a><br><br>新浪公司　<a target="_blank" href="http://www.sina.com.cn/intro/copyright.shtml">版权所有</a>
</div>

<!-- end footer -->
</div>
</body>
</html>