<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-type" content="text/html; charset=gb2312" />
<title>最新滚动研究报告|研究评级|机构研报_新浪财经_新浪网</title>
<meta name="keywords" content="最新滚动研究报告,最新滚动机构研报" />
<meta name="description" content="新浪财经最新滚动行情中心,为您提供最新滚动研究报告,研究评级,机构研报信息查询." />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" / >
<script type="text/javascript" src="http://www.sinaimg.cn/jslib/jquery-1.4.2.min.js"></script>
<style type="text/css">
/* 初始化CSS */
html, body, ul, li, ol, dl, dd, dt, p, h1, h2, h3, h4, h5, h6, form, fieldset, legend,img{margin:0;padding:0;}
fieldset,img{border:none;}
address,caption,cite,code,dfn,th,var{font-style:normal;font-weight:normal;}
ul,ol{list-style:none;}
select,input{vertical-align:middle;}
select,input,textarea{font-size:12px;margin:0;}
table{border-collapse:collapse;}
body{background:#fff;color:#4e4e4e;padding:5px 0;font:12px/20px "宋体";}

.clearfix:after{content:".";display:block;height:0;visibility:hidden;clear:both;}
.clearfix{zoom:1;}
.clearit{clear:both;height:0;font-size:0;overflow:hidden;}

a{color:#009;text-decoration:none;}
a:visited{color:#800080;}
a:hover, a:active, a:focus{color:#f00;text-decoration:underline;}

a.linkRed:link,a.linkRed:visited{color:#f00!important;}/* 红色 */
a.linkRed:hover{color:#c00!important;}
a.linkRed01:link,a.linkRed01:visited{color:red!important}
a.linkRed01:hover{color:red!important}

/*自定义链接颜色*/
.fred { color:#f00 !important}
.fblack { color:#000 !important}
.fblue { color:#33F !important}
.forange { color:#F60 !important}
.fred:visited, .fblack:visited, .fblue:visited, .forange:visited{color:#800080 !important}
.fred:hover, .fblack:hover, .fblue:hover, .forange:hover{color:#f00 !important}

/*自定义标题链接颜色*/
.f_red, .f_red:visited, .f_red:hover { color:#f00 !important}
.f_black, .f_black:visited, .f_black:hover { color:#000 !important}
.f_blue, .f_blue:visited, .f_blue:hover { color:#18479B !important}
.f_orange, .f_orange:visited, .f_orange:hover { color:#F60 !important}

.space { height:10px; overflow:hidden; background:#fff; }
.isLine { text-decoration:underline !important; }
.f12 { font-size:12px !important}
.f14 { font-size:14px !important}
.f16 { font-size:16px !important}
.lh23 { line-height:23px !important }
.lh24 { line-height:24px !important }
.lh30 { line-height:30px !important }
.left{float:left}
.right{float:right}
.tal{text-align:left !important}
.tar{text-align:right !important}
.bold{ font-weight:bold;}
.nobottom{border-bottom:none !important}
.nobg{background:none !important}
h1, h2, h3, h4, h5, strong { font-weight:normal; }
.wrap { width:950px; margin:0 auto; }
/* 导航 */
.navTop {}
.navTop .nav01{background:url(/q/view/image/finance_zxh_0406_01.png) repeat-x; border:solid 1px #0988d2; line-height:33px; height:33px;}
.nav01 ul{height:25px; padding:4px 0}
.nav01 li{float:left; font-size:14px; padding:0 14px; height:25px; line-height:25px;}
.nav01 li.home{background:url(/q/view/image/finance_zxh_0406_01.png) no-repeat 0 -37px; width:130px; text-indent:-999em;overflow:hidden}
.nav01 li.current{ color:#fff79d; margin:0 14px; padding:0 9px; border:solid 1px #2aa6f1; background:url(/q/view/image/finance_zxh_0406_01.png) no-repeat 0 -77px; height:23px;}
.nav01 li.line{ border-left:solid 1px #0967bb; padding:0; margin-top:6px; border-right:solid 1px #9ad4f9; height:11px; width:0; overflow:hidden; font-size:0}
.nav02{ border:solid 1px #d8d8d8; background:#f3f3f3; line-height:20px; padding:5px 0 5px 18px; height:20px; font-family:Tahoma; vertical-align:middle}
.nav02 .radio{vertical-align: middle}
.navTop a:link, .navTop a:visited { color:#fff; display:block;}
.navTop a:hover { color:#fff;}
/* ============== 横切定义 ============== */
.main{border:solid 1px #d4dce7; margin-top:10px;}
/* ================== block define ================== */
/* 板块单独定义 */
.blk_01, .blk_01 form { vertical-align:middle}
.blk a:visited{ color:#800080;}
.blk a:hover{color:#c00;}
/* ================= commen define ================ */
/* 标题 */
.tb_01{}
.tb_01 th{background:#f6f9fa; border-bottom:solid 1px #d4dce7; line-height:28px; height:28px; text-align:center;}
.tb_01 td{ height:27px; line-height:27px; text-align:center; background:#fcfdfe}
.tb_01 td.f14{ padding-left:15px;}
.tb_01 .t01{ width:40px}
.tb_01 .t02{ padding-left:136px; text-align:left}
.tb_01 .t03{ width:110px}
.tb_01 .t04{ width:90px}
.tb_01 .t05{ width:144px;}
.tb_01 .fname05{ width:152px; height:20px; overflow:hidden}
.tb_01 .fname05 span{ display:block; width:800px; text-align:left; padding-left:10px;}
.tb_01 .t06{ width:74px; padding-left:10px; text-align:left}
.tb_01 .fname{ width:82px; height:20px; overflow:hidden}
.tb_01 .fname span{ display:block; width:800px; text-align:left; padding-left:10px;}
.tb_01 td.td10{ height:10px; overflow:hidden}
.tb_01 a:link{color:#18479b}
.tb_01 a:visited{color:#800080}
.tb_01 a:hover{ color:#0677d6;}
/* 分页 */
.page{background:url(/q/view/image/finance_zxh_0406_02.png) repeat-x; padding:20px 0; margin:20px;}
.pagebox{overflow:hidden; zoom:1; font-size:12px; font-family:"宋体",sans-serif;}
.pagebox span{float:left; margin-right:2px; overflow:hidden; text-align:center; background:#fff;}
.pagebox span a{display:block; overflow:hidden; zoom:1; _float:left;}
.pagebox span.pagebox_pre_nolink{border:1px #ddd solid; width:53px; height:21px; line-height:21px; text-align:center; color:#999; cursor:default;}
.pagebox span.pagebox_pre{color:#3568b9; height:23px;}
.pagebox span.pagebox_pre a,.pagebox span.pagebox_pre a:visited,.pagebox span.pagebox_next a,.pagebox span.pagebox_next a:visited{border:1px #c2c1c1 solid; background:#f5f4f4; color:#18479b; text-decoration:none; text-align:center; width:53px; cursor:pointer; height:21px; line-height:21px;}
.pagebox span.pagebox_pre a:hover,.pagebox span.pagebox_pre a:active,.pagebox span.pagebox_next a:hover,.pagebox span.pagebox_next a:active{color:#363636; border:1px #2e6ab1 solid;}
.pagebox span.pagebox_num_nonce{padding:0 8px; height:23px; line-height:23px; color:#fff; cursor:default; background:#09a9ec; font-weight:bold;}
.pagebox span.pagebox_num{color:#3568b9; height:23px;}
.pagebox span.pagebox_num a,.pagebox span.pagebox_num a:visited{border:1px #c2c1c1 solid; color:#18479b; background:#f5f4f4; text-decoration:none; padding:0 8px; cursor:pointer; height:21px; line-height:21px;}
.pagebox span.pagebox_num a:hover,.pagebox span.pagebox_num a:active{border:1px #2e6ab1 solid;color:#363636;}
.pagebox span.pagebox_num_ellipsis{color:#393733; width:22px; background:none; line-height:23px;}
.pagebox span.pagebox_next_nolink{border:1px #ddd solid; width:53px; height:21px; line-height:21px; text-align:center; color:#999; cursor:default;}
</style>
<script type="text/javascript">
        function url_set_search(key,value,clear){
            var search = window.location.search;
            var pathname = window.location.pathname;
            var keyValue = new Array();
            if(search && search.charAt(0) == '?'){
                search = search.substr(1);
            }
            var flag = false;
            if(search && !clear){
                var arr = search.split('&');
                for(var i =0;i<arr.length;i++){
                    var tmp = arr[i].split('=');
                    if(tmp[0]==key){
                        if(value){
                            keyValue.push(key+"="+encodeURIComponent(value));
                        }
                        flag = true;
                    }
                    else{
                        keyValue.push(arr[i]);
                    }
                }
            }
            if(flag == false){
                keyValue.push(key+"="+encodeURIComponent(value));
            }
            search = keyValue.join("&");
            search = search?"?"+search:"";
            window.open(pathname+search,'_self');

            if(event){
                if (event.stopPropagation)
                event.stopPropagation();
                if (event.preventDefault)
                event.preventDefault();
                event.cancelBubble = true;
                event.returnValue = false;
            }
            return false;
        }
        function set_page_num(number){
            url_set_search('p',number,false);
        }
</script>
</head>
<body>
<div class="wrap">
  <!-- 标准二级导航_财经 begin -->
  <style type="text/css">
.secondaryHeader{height:33px;overflow:hidden;background:url(http://i2.sinaimg.cn/dy/images/header/2008/standardl2nav_bg.gif) repeat-x #fff;color:#000;font-size:12px;font-weight:100;}
.secondaryHeader a,.secondaryHeader a:visited{color:#000;text-decoration:none;}
.secondaryHeader a:hover,.secondaryHeader a:active{color:#c00;text-decoration:underline;}
.sHBorder{border:1px #e3e3e3 solid;padding:0 10px 0 12px;overflow:hidden;zoom:1;}
.sHLogo{float:left;height:31px;line-height:31px;overflow:hidden;}
.sHLogo span,.sHLogo span a,.sHLogo span a:link,.sHLogo span a:visited,.sHLogo span a:hover{display:block;*float:left;display:table-cell;vertical-align:middle;*display:block;*font-size:27px;*font-family:Arial;height:31px;}
.sHLogo span,.sHLogo span a img,.sHLogo span a:link img,.sHLogo span a:visited img,.sHLogo span a:hover img{vertical-align:middle;}
.sHLinks{float:right;line-height:31px;}
</style>
  <script type="text/javascript" src="http://finance.sina.com.cn/stock/reaserchyjbg/report/report_industry.js"></script>
<script type="text/javascript" src="http://finance.sina.com.cn/stock/reaserchyjbg/report/report_orgname.js"></script>
<script type="text/javascript" src="http://www.sinaimg.cn/cj/financewidget/js/Calendar_1.0.1.js"></script>
<div class="secondaryHeader">
    <div class="sHBorder">
      <div class="sHLogo"><span><a href="http://finance.sina.com.cn/"><img src="http://i1.sinaimg.cn/dy/images/header/2009/standardl2nav_sina_new.gif" alt="新浪网" /></a><a href="http://finance.sina.com.cn/"><img src="http://i1.sinaimg.cn/dy/images/header/2009/standardl2nav_finance.gif" alt="新浪财经" /></a></span></div>
      <div class="sHLinks"><a href="http://finance.sina.com.cn/">财经首页</a>&nbsp;|&nbsp;<a href="http://www.sina.com.cn/">新浪首页</a>&nbsp;|&nbsp;<a href="http://news.sina.com.cn/guide/">新浪导航</a></div>
    </div>
  </div>
  <!-- 标准二级导航_财经 end -->
  <!-- 导航 begin -->
  <div class="navTop">
    <div class="nav01">
      <ul>
        <li class="home">
            <a href="http://finance.sina.com.cn/stock/report/index.shtml">研究报告</a>
        </li>
        <li class="current">最新滚动</li>        <li class="line"></li>
        <li>
            <a href="http://roll.finance.sina.com.cn/finance/zq1/zldx/index.shtml">主力动向</a>
        </li>
        <li class="line"></li>
        <li>
            <a href="http://vip.stock.finance.sina.com.cn/q/go.php/vIR_RatingNewest/index.phtml">个股评级</a>
        </li>
        <li class="line"></li>
        <li><a href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/company/index.phtml">公司研究</a></li>        <li class="line"></li>
        <li><a href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/industry/index.phtml">行业研究</a></li>        <li class="line"></li>
        <li><a href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/strategy/index.phtml">投资策略</a></li>        <li class="line"></li>
        <li><a href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/macro/index.phtml">宏观研究</a></li>        <li class="line"></li>
        <li>
            <a href="http://vip.stock.finance.sina.com.cn/q/go.php/vInvestConsult/kind/qgqp/index.phtml">个股点评</a>
        </li>
      </ul>
    </div>
        <script type="text/javascript" src="http://www.sinaimg.cn/cj/financewidget/js/SuggestServer_3_0_19.js"></script>
    <script type="text/javascript">(new SuggestServer()).bind({"input": "key", "value": "@3@", "type": "stock", "width": 180, "target":"_self","link": "/q/go.php/vIR_StockSearch/key/@2@.phtml"});</script>
    <script type="text/javascript">    jQuery.noConflict();</script>
    <script type="text/javascript">
        var _industry = '';
        var _orgname = '';
        var searchType = 'title';
        function checkForm()
        {
            if(searchType == 'stock'){
                var symbol = jQuery.trim(jQuery('#symbol').val());
                if(symbol == '')
                    return false;
                else{
                    var pattern = /^(sh|sz)?[0-9]{6}$/;
                    var rs = pattern.test(symbol);
                    if(rs == false){
                        alert('不正确的股票代码');
                        return false;
                    }
                }
            }else if(jQuery.trim(jQuery('#'+searchType).val()) == '')
                return false;
            return true;
        }
        function search(t)
        {
            searchType = t;
            switch(t)
            {
                case 'stock':
                    jQuery('#symbol').show();
					jQuery('#pubdate').hide();
                    jQuery('#searchInner').html('');
                    break;
				case 'pubdate':
					jQuery('#symbol').hide();
					jQuery('#pubdate').show();
                    jQuery('#searchInner').html('');
					break;
                case 'analysts':
                case 'title':
                    var c = '<input name="'+t+'" id="'+t+'" type="text" size="20">';
                    jQuery('#searchInner').html(c);
                    jQuery('#symbol').hide();
					jQuery('#pubdate').hide();
                    break;
                case 'orgname':
                    if(_orgname == '')
                    {
                        var _listWithoutID = ['reportOrgname'];
                        var _list;
                        for(var i = 0;i < _listWithoutID.length;i++)
                        {
                            _list = window[_listWithoutID[i]] || [];
                            _orgname = jQuery('<select name="orgname" id="orgname">');
                            for(var j = 0;j < _list.length;j++)
                            {
                                _orgname.append(jQuery('<option value="'+_list[j].svalue + '">').html(_list[j].svalue));
                            }
                        }
                    }
                    jQuery('#searchInner').html(_orgname);
                    jQuery('#symbol').hide();
					jQuery('#pubdate').hide();
                    break;
                case 'industry':
                    if(_industry == '')
                    {
                        var _listWithoutID = ['reportIndustry'];
                        var _list;
                        for(var i = 0;i < _listWithoutID.length;i++)
                        {
                            _list = window[_listWithoutID[i]] || [];
                            _industry = jQuery('<select name="industry" id="industry">');
                            for(var j = 0;j < _list.length;j++)
                            {
                                _industry.append(jQuery('<option value="'+_list[j].svalue + '">').html(_list[j].svalue));
                            }
                        }
                    }
                    jQuery('#searchInner').html(_industry);
                    jQuery('#symbol').hide();
					jQuery('#pubdate').hide();
                    break;
                default:
                    break;
            }
        }
        jQuery(document).ready(function(){
			jQuery('#pubdate').hide();
            var t1 = '';
            if(t1 != '' && t1 != 'all')
            {
                jQuery('#t1_'+t1).click();
                if(t1 == '1'){
                    jQuery('#orgname').val('');
                }else if(t1 == '2'){
                    jQuery('#symbol').val('');
                }else if(t1 == '3'){
                    jQuery('#industry').val('');
                }else if(t1 == '4'){
                    jQuery('#analysts').val('');
                }else if(t1 == '5'){
                    jQuery('#title').val('');
                }else if(t1 == '6'){
                    jQuery('#pubdate').val('');
                }
            }
            else
            {
                jQuery('#t1_6').click();
            }
        })
    </script>
    <div class="nav02">
        <div class="blk_01">
        <form method="get" action="/q/go.php/vReport_List/kind/search/index.phtml" onsubmit="return checkForm()" style="position:relative;">
            <span class="f_blue">研报搜索：</span>
            <input type="radio" name="t1" class="radio" id="t1_1" value="1" onclick="search('orgname')" /> 研究机构
            <input type="radio" name="t1" class="radio" id="t1_2" value="2" onclick="search('stock')" /> 公司股票
            <input type="radio" name="t1" class="radio" id="t1_3" value="3" onclick="search('industry')" /> 行业分类
            <input type="radio" name="t1" class="radio" id="t1_4" value="4" onclick="search('analysts')" /> 分析师
            <input type="radio" name="t1" class="radio" id="t1_5" value="5" onclick="search('title')"/> 标题
			<input type="radio" name="t1" class="radio" id="t1_6" value="6" onclick="search('pubdate')"/> 发布日期
            <span id="searchInner">
                <!--input name="title" id="title" type="text" size="20"-->
            </span>
            <input name="symbol" id="symbol" type="text" size="20" style="display:none" />
			<input name="pubdate" id="pubdate" type="text" size="20" value="2019-10-09" />
            <input type="submit" value="搜索" class="search_btn" />
            <script type="text/javascript">
				(new SuggestServer()).bind({"input": "symbol", "value": "@3@", "type": "stock", "width": 180});
				var calendar = new Calendar("pubdate", false, false, [155, 800, 0.95, "solid", "#EEE", "#FFF", 3, 3, 0.2, "#000", "#444", "#F6F8FD", "#333", "#F1F5FC", "#000", "#EFF3FB", false, false]);
			</script>
        </form>
        </div>
    </div>
</div>
  <!-- 导航 end -->

  <!-- main -->
  <div class="main">
   <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tb_01">
  <tr>
    <th scope="col" class="t01">序号</th>
    <th scope="col" class="t02">标题</th>
    <th scope="col" class="t03">报告类型</th>
    <th scope="col" class="t04">发布日期</th>
    <th scope="col" class="t05">机构</th>
    <th scope="col" class="t06">研究员</th>
  </tr>
  <tr>
    <td colspan="6" class="td10"></td>
  </tr>
            <tr>
            <td>1</td>
            <td class="tal f14">
                <a target="_blank" title="千禾味业公司动态点评:聚焦零添加,静待加速成长" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727308/index.phtml">
                    千禾味业公司动态点评:聚焦零添加,静待加速成长                </a>
            </td>
            <td>公司研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B3%A4%B3%C7%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>长城证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>张宇光,黄瑞云</span></div></td>
     </tr>
           <tr>
            <td>2</td>
            <td class="tal f14">
                <a target="_blank" title="有色金属行业周报:贸易谈判再起波澜,避险情绪升温支撑贵金属价格" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727304/index.phtml">
                    有色金属行业周报:贸易谈判再起波澜,避险情绪升温支撑贵金属价格                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%FA%CA%A2%D6%A4%C8%AF%D3%D0%CF%DE%D4%F0%C8%CE%B9%AB%CB%BE">
                    <div class="fname05"><span>国盛证券有限责任公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>丁婷婷</span></div></td>
     </tr>
           <tr>
            <td>3</td>
            <td class="tal f14">
                <a target="_blank" title="石油化工行业8月动态报告:石油化工行业景气回落,看好下游改性塑料加工环节投资机会" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727302/index.phtml">
                    石油化工行业8月动态报告:石油化工行业景气回落,看好下游改性...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%D6%D0%B9%FA%D2%F8%BA%D3%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>中国银河证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>刘兰程</span></div></td>
     </tr>
           <tr>
            <td>4</td>
            <td class="tal f14">
                <a target="_blank" title="电气设备行业跟踪报告:2019年7月新能源汽车产业数据跟踪分析-供给创造需求" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727300/index.phtml">
                    电气设备行业跟踪报告:2019年7月新能源汽车产业数据跟踪分...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BB%AA%B4%B4%D6%A4%C8%AF%D3%D0%CF%DE%D4%F0%C8%CE%B9%AB%CB%BE">
                    <div class="fname05"><span>华创证券有限责任公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>胡毅,于潇,邱迪</span></div></td>
     </tr>
           <tr>
            <td>5</td>
            <td class="tal f14">
                <a target="_blank" title="化工行业周观点:万华上调9月MDI挂牌价,DSM整合能特VE产能" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727298/index.phtml">
                    化工行业周观点:万华上调9月MDI挂牌价,DSM整合能特VE产能                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%CE%F7%C4%CF%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>西南证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>杨林,黄景文,周峰春</span></div></td>
     </tr>
           <tr>
            <td>6</td>
            <td class="tal f14">
                <a target="_blank" title="石油化工行业周报:从海外炼化的投资成本与进度,来看民营大炼化竞争力" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727296/index.phtml">
                    石油化工行业周报:从海外炼化的投资成本与进度,来看民营大炼化...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%C9%EA%CD%F2%BA%EA%D4%B4%BC%AF%CD%C5%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>申万宏源集团股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>谢建斌,宋涛,叶旭晨</span></div></td>
     </tr>
           <tr>
            <td>7</td>
            <td class="tal f14">
                <a target="_blank" title="轻工制造行业周报:双节临近,中小纸厂纷纷喊涨原纸价格" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727294/index.phtml">
                    轻工制造行业周报:双节临近,中小纸厂纷纷喊涨原纸价格                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BB%AA%BD%F0%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>华金证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>叶中正,杨维维</span></div></td>
     </tr>
           <tr>
            <td>8</td>
            <td class="tal f14">
                <a target="_blank" title="交通运输行业周报:快递龙头持续领跑,关注油运行情" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727292/index.phtml">
                    交通运输行业周报:快递龙头持续领跑,关注油运行情                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%FA%CA%A2%D6%A4%C8%AF%D3%D0%CF%DE%D4%F0%C8%CE%B9%AB%CB%BE">
                    <div class="fname05"><span>国盛证券有限责任公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>张俊</span></div></td>
     </tr>
           <tr>
            <td>9</td>
            <td class="tal f14">
                <a target="_blank" title="石化行业周报:美油库存大降,产量再创纪录新高" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727290/index.phtml">
                    石化行业周报:美油库存大降,产量再创纪录新高                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%C3%F1%C9%FA%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>民生证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>杨侃,李晓辉</span></div></td>
     </tr>
           <tr>
            <td>10</td>
            <td class="tal f14">
                <a target="_blank" title="新能源汽车行业数据周跟踪:宁德时代全球首款CTP电池包应用于北汽新能源EU5" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727288/index.phtml">
                    新能源汽车行业数据周跟踪:宁德时代全球首款CTP电池包应用于...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%C3%F1%C9%FA%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>民生证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>杨睿,李唯嘉</span></div></td>
     </tr>
           <tr>
            <td>11</td>
            <td class="tal f14">
                <a target="_blank" title="生物医药行业周报:国产新药临床数据优异,继续推荐创新产业链" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727286/index.phtml">
                    生物医药行业周报:国产新药临床数据优异,继续推荐创新产业链                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%C6%BD%B0%B2%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>平安证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>叶寅,张熙</span></div></td>
     </tr>
           <tr>
            <td>12</td>
            <td class="tal f14">
                <a target="_blank" title="食品饮料行业周报:白酒板块关注茅台一批价走势,大众品寻找低估值细分龙头" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727285/index.phtml">
                    食品饮料行业周报:白酒板块关注茅台一批价走势,大众品寻找低估...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%FA%BA%A3%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>国海证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>余春生</span></div></td>
     </tr>
           <tr>
            <td>13</td>
            <td class="tal f14">
                <a target="_blank" title="化工行业周报:9月MDI展望:提价是反转还是涨价去库存?" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727282/index.phtml">
                    化工行业周报:9月MDI展望:提价是反转还是涨价去库存?                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%D5%E3%C9%CC%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>浙商证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>范飞</span></div></td>
     </tr>
           <tr>
            <td>14</td>
            <td class="tal f14">
                <a target="_blank" title="建筑材料行业周报:旺季涨价逐渐扩散" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727280/index.phtml">
                    建筑材料行业周报:旺季涨价逐渐扩散                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%FA%CA%A2%D6%A4%C8%AF%D3%D0%CF%DE%D4%F0%C8%CE%B9%AB%CB%BE">
                    <div class="fname05"><span>国盛证券有限责任公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>黄诗涛,房大磊,石峰源</span></div></td>
     </tr>
           <tr>
            <td>15</td>
            <td class="tal f14">
                <a target="_blank" title="汽车行业周报:工信部研究设立燃油汽车禁行区试点" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727278/index.phtml">
                    汽车行业周报:工信部研究设立燃油汽车禁行区试点                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%C9%CF%BA%A3%D6%A4%C8%AF%D3%D0%CF%DE%D4%F0%C8%CE%B9%AB%CB%BE">
                    <div class="fname05"><span>上海证券有限责任公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>黄涵虚</span></div></td>
     </tr>
           <tr>
            <td>16</td>
            <td class="tal f14">
                <a target="_blank" title="公用事业行业周报(第三十四周)" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727276/index.phtml">
                    公用事业行业周报(第三十四周)                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BB%AA%CC%A9%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>华泰证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>王玮嘉</span></div></td>
     </tr>
           <tr>
            <td>17</td>
            <td class="tal f14">
                <a target="_blank" title="银行业周报181期:香港投资者的主要关注点" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727274/index.phtml">
                    银行业周报181期:香港投资者的主要关注点                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%D6%D0%D0%C5%BD%A8%CD%B6%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>中信建投证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>杨荣</span></div></td>
     </tr>
           <tr>
            <td>18</td>
            <td class="tal f14">
                <a target="_blank" title="广发港股行业周度观点:英国“无协议脱欧”风险上升" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727272/index.phtml">
                    广发港股行业周度观点:英国“无协议脱欧”风险上升                </a>
            </td>
            <td>投资策略</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%E3%B7%A2%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>广发证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>广发证券研究所</span></div></td>
     </tr>
           <tr>
            <td>19</td>
            <td class="tal f14">
                <a target="_blank" title="非银金融2019年秋季投资策略报告:金融业开放视角下的保险行业发展回顾与前瞻" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727270/index.phtml">
                    非银金融2019年秋季投资策略报告:金融业开放视角下的保险行...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%D6%D0%D0%C5%BD%A8%CD%B6%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>中信建投证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>赵然</span></div></td>
     </tr>
           <tr>
            <td>20</td>
            <td class="tal f14">
                <a target="_blank" title="金工量化周报:继续关注成长和消费板块,8月行业组合完美收官战胜基准3.23%" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727268/index.phtml">
                    金工量化周报:继续关注成长和消费板块,8月行业组合完美收官战...                </a>
            </td>
            <td>投资策略</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%C9%EA%CD%F2%BA%EA%D4%B4%BC%AF%CD%C5%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>申万宏源集团股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>曹春晓</span></div></td>
     </tr>
           <tr>
            <td>21</td>
            <td class="tal f14">
                <a target="_blank" title="建筑材料周期行业数据周报(第三十二周)" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727266/index.phtml">
                    建筑材料周期行业数据周报(第三十二周)                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BB%AA%CC%A9%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>华泰证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>华泰证券研究所</span></div></td>
     </tr>
           <tr>
            <td>22</td>
            <td class="tal f14">
                <a target="_blank" title="钢铁行业重大事项点评:库存和成交快评:减产继续库存下降,表观需求略有回调" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727264/index.phtml">
                    钢铁行业重大事项点评:库存和成交快评:减产继续库存下降,表观...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BB%AA%B4%B4%D6%A4%C8%AF%D3%D0%CF%DE%D4%F0%C8%CE%B9%AB%CB%BE">
                    <div class="fname05"><span>华创证券有限责任公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>任志强,严鹏</span></div></td>
     </tr>
           <tr>
            <td>23</td>
            <td class="tal f14">
                <a target="_blank" title="非银金融行业周报:中报符合预期,外资如期入市" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727262/index.phtml">
                    非银金融行业周报:中报符合预期,外资如期入市                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B0%AE%BD%A8%D6%A4%C8%AF%D3%D0%CF%DE%D4%F0%C8%CE%B9%AB%CB%BE">
                    <div class="fname05"><span>爱建证券有限责任公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>方采薇</span></div></td>
     </tr>
           <tr>
            <td>24</td>
            <td class="tal f14">
                <a target="_blank" title="汽车行业重大事项点评:本轮对美加征汽车关税有哪些影响?" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727260/index.phtml">
                    汽车行业重大事项点评:本轮对美加征汽车关税有哪些影响?                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BB%AA%B4%B4%D6%A4%C8%AF%D3%D0%CF%DE%D4%F0%C8%CE%B9%AB%CB%BE">
                    <div class="fname05"><span>华创证券有限责任公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>张程航,王俊杰</span></div></td>
     </tr>
           <tr>
            <td>25</td>
            <td class="tal f14">
                <a target="_blank" title="建筑装饰行业半年度订单汇总分析:建筑央企新签订单回暖,子行业内公司两级分化持续" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727258/index.phtml">
                    建筑装饰行业半年度订单汇总分析:建筑央企新签订单回暖,子行业...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%CC%EC%B7%E7%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>天风证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>唐笑,肖文劲,岳恒宇</span></div></td>
     </tr>
           <tr>
            <td>26</td>
            <td class="tal f14">
                <a target="_blank" title="社会服务业行业研究:宋城演艺中报表现符合预期,中免上海市内免税店开业" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727257/index.phtml">
                    社会服务业行业研究:宋城演艺中报表现符合预期,中免上海市内免...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%FA%BD%F0%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>国金证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>楼枫烨,卞丽娟</span></div></td>
     </tr>
           <tr>
            <td>27</td>
            <td class="tal f14">
                <a target="_blank" title="5G趋势之OTT行业专题报告:电视的未来,OTT的新时代" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727253/index.phtml">
                    5G趋势之OTT行业专题报告:电视的未来,OTT的新时代                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%FA%CC%A9%BE%FD%B0%B2%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>国泰君安证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>陈筱,陈融,苗瑜</span></div></td>
     </tr>
           <tr>
            <td>28</td>
            <td class="tal f14">
                <a target="_blank" title="休闲服务行业2019年周报第31期:上半年全行业实现营收659.7亿元,增速放缓" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727251/index.phtml">
                    休闲服务行业2019年周报第31期:上半年全行业实现营收65...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%FA%C1%AA%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>国联证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>钱建</span></div></td>
     </tr>
           <tr>
            <td>29</td>
            <td class="tal f14">
                <a target="_blank" title="燃气水务行业周报:发改委,将千方百计保障今冬明春天然气供应" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727249/index.phtml">
                    燃气水务行业周报:发改委,将千方百计保障今冬明春天然气供应                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%C9%CF%BA%A3%D6%A4%C8%AF%D3%D0%CF%DE%D4%F0%C8%CE%B9%AB%CB%BE">
                    <div class="fname05"><span>上海证券有限责任公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>冀丽俊</span></div></td>
     </tr>
           <tr>
            <td>30</td>
            <td class="tal f14">
                <a target="_blank" title="非银金融行业:券商股迎上车机会,保险股中报业绩优异" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727245/index.phtml">
                    非银金融行业:券商股迎上车机会,保险股中报业绩优异                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%D6%D0%D0%C5%BD%A8%CD%B6%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>中信建投证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>赵然</span></div></td>
     </tr>
           <tr>
            <td>31</td>
            <td class="tal f14">
                <a target="_blank" title="机械设备行业:手持激光焊兴起,焊接市场替代空间巨大" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727243/index.phtml">
                    机械设备行业:手持激光焊兴起,焊接市场替代空间巨大                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%FA%CA%A2%D6%A4%C8%AF%D3%D0%CF%DE%D4%F0%C8%CE%B9%AB%CB%BE">
                    <div class="fname05"><span>国盛证券有限责任公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>姚健,罗政</span></div></td>
     </tr>
           <tr>
            <td>32</td>
            <td class="tal f14">
                <a target="_blank" title="军工行业点评:国庆阅兵规模超往年,军工板块九月或将迎来超额收益" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727241/index.phtml">
                    军工行业点评:国庆阅兵规模超往年,军工板块九月或将迎来超额收益                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%D6%D0%B9%FA%D2%F8%BA%D3%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>中国银河证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>李良</span></div></td>
     </tr>
           <tr>
            <td>33</td>
            <td class="tal f14">
                <a target="_blank" title="教育行业周报:国家支持职业教育,政策或将再加码,坚定看好职教行业" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727239/index.phtml">
                    教育行业周报:国家支持职业教育,政策或将再加码,坚定看好职教...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%C3%F1%C9%FA%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>民生证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>强超廷</span></div></td>
     </tr>
           <tr>
            <td>34</td>
            <td class="tal f14">
                <a target="_blank" title="长亮科技:三季度实际利润超预期,金融自主可控和海外市场加速成长" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727237/index.phtml">
                    长亮科技:三季度实际利润超预期,金融自主可控和海外市场加速成长                </a>
            </td>
            <td>公司研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%FA%CA%A2%D6%A4%C8%AF%D3%D0%CF%DE%D4%F0%C8%CE%B9%AB%CB%BE">
                    <div class="fname05"><span>国盛证券有限责任公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>刘高畅,杨然</span></div></td>
     </tr>
           <tr>
            <td>35</td>
            <td class="tal f14">
                <a target="_blank" title="建筑装饰行业研究周报:上半年业绩分化显著,部分建筑股估值正在修复" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727235/index.phtml">
                    建筑装饰行业研究周报:上半年业绩分化显著,部分建筑股估值正在...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%CC%EC%B7%E7%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>天风证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>唐笑,肖文劲,岳恒宇</span></div></td>
     </tr>
           <tr>
            <td>36</td>
            <td class="tal f14">
                <a target="_blank" title="交通运输行业周报:拼多多将如何布局“新物流”平台?" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727233/index.phtml">
                    交通运输行业周报:拼多多将如何布局“新物流”平台?                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%FA%BD%F0%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>国金证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>孙春旭</span></div></td>
     </tr>
           <tr>
            <td>37</td>
            <td class="tal f14">
                <a target="_blank" title="宋城演艺:珠海演艺谷进入规划建设期,公司转型扩张持续推进" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727231/index.phtml">
                    宋城演艺:珠海演艺谷进入规划建设期,公司转型扩张持续推进                </a>
            </td>
            <td>公司研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%C9%EA%CD%F2%BA%EA%D4%B4%BC%AF%CD%C5%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>申万宏源集团股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>刘乐文</span></div></td>
     </tr>
           <tr>
            <td>38</td>
            <td class="tal f14">
                <a target="_blank" title="计算机行业周报:金融科技发展规划出台,上市公司分拆子公司上市试点" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727229/index.phtml">
                    计算机行业周报:金融科技发展规划出台,上市公司分拆子公司上市...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%CE%F7%C4%CF%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>西南证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>朱芸</span></div></td>
     </tr>
           <tr>
            <td>39</td>
            <td class="tal f14">
                <a target="_blank" title="金地集团2019年9月销售数据点评:销售持续大增,料全年超2000亿" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727227/index.phtml">
                    金地集团2019年9月销售数据点评:销售持续大增,料全年超2000亿                </a>
            </td>
            <td>公司研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%BB%AA%B4%B4%D6%A4%C8%AF%D3%D0%CF%DE%D4%F0%C8%CE%B9%AB%CB%BE">
                    <div class="fname05"><span>华创证券有限责任公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>袁豪,曹曼</span></div></td>
     </tr>
           <tr>
            <td>40</td>
            <td class="tal f14">
                <a target="_blank" title="食品饮料行业周报:白酒板块受“双节”影响股价催化明显,关注个别低估值大众品标的" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_Show/kind/lastest/rptid/4727225/index.phtml">
                    食品饮料行业周报:白酒板块受“双节”影响股价催化明显,关注个...                </a>
            </td>
            <td>行业研究</td>
            <td>2019-10-09</td>
            <td>
                <a target="_blank" href="http://vip.stock.finance.sina.com.cn/q/go.php/vReport_List/kind/search/index.phtml?t1=1&orgname=%B9%FA%BA%A3%D6%A4%C8%AF%B9%C9%B7%DD%D3%D0%CF%DE%B9%AB%CB%BE">
                    <div class="fname05"><span>国海证券股份有限公司</span></div>
                </a>
            </td>
            <td><div class="fname"><span>余春生</span></div></td>
     </tr>
   </table>
<!-- 分页 begin -->
<div class="page">
<table cellspacing="0" style="margin:0 auto;"><tr><td>
<div class="pagebox" id="_function_code_page">
     <span class='pagebox_pre_nolink'>首页</span>  <span class='pagebox_pre_nolink'>上一页</span>  <span class='pagebox_num_nonce'>1</span>  <span class='pagebox_num'><a href="javascript:void(0)" onclick="set_page_num('2')">2</a></span>  <span class='pagebox_num'><a href="javascript:void(0)" onclick="set_page_num('3')">3</a></span>  <span class='pagebox_num'><a href="javascript:void(0)" onclick="set_page_num('4')">4</a></span>  <span class='pagebox_num'><a href="javascript:void(0)" onclick="set_page_num('5')">5</a></span>  <span class='pagebox_num'><a href="javascript:void(0)" onclick="set_page_num('6')">6</a></span>  <span class='pagebox_next'><a href="javascript:void(0)" onclick="set_page_num('2')">下一页</a></span>  <span class='pagebox_next'><a href="javascript:void(0)" onclick="set_page_num('7473')">最末页</a></span> </div>
</td></tr></table>
</div>
<!-- 分页 end -->
  </div>
<!-- end main -->
<!-- footer -->

<style type="text/css">
#footer{width:950px; text-align:center; line-height:21px; font-size:12px;margin-top:20px;color:#333;margin-left:auto;margin-right:auto;}
#footer a:link{color:#000099}
#footer a:visited{color:#800080}
#footer a:hover{color:#ff0000;text-decoration:underline;}
#footer a:active {color:#0100A3; text-decoration:none;}
</style>
<!-- SUDA_CODE_START --> 
<script type="text/javascript" src="//www.sinaimg.cn/unipro/pub/suda_s_v851c.js"></script>
<script type="text/javascript" > 
_S_pSt(_S_PID_); 
</script>
<!-- SUDA_CODE_END -->

<div id="footer">
客户服务热线：4000520066　　
欢迎批评指正<br>

<a target="_blank" href="http://tech.sina.com.cn/focus/sinahelp.shtml">常见问题解答</a>  
<a target="_blank" href="http://net.china.cn/chinese/index.htm">互联网违法和不良信息举报</a>　
<a target="_blank" href="https://gu.sina.cn/pc/feedback/">新浪财经意见反馈留言板</a>
<br><br>
<a href="http://corp.sina.com.cn/chn/">新浪简介</a> | <a href="http://corp.sina.com.cn/eng/">About Sina</a> | <a href="http://emarketing.sina.com.cn/">广告服务</a> | <a href="http://www.sina.com.cn/contactus.html">联系我们</a> | <a href="http://corp.sina.com.cn/chn/sina_job.html">招聘信息</a> | <a href="http://www.sina.com.cn/intro/lawfirm.shtml">网站律师</a> | <a href="http://english.sina.com">SINA English</a> | <a href="http://members.sina.com.cn/apply/">通行证注册</a> | <a href="http://help.sina.com.cn/">产品答疑</a><br><br>新浪公司　<a target="_blank" href="http://www.sina.com.cn/intro/copyright.shtml">版权所有</a>
</div>

<!-- end footer -->
</div>
</body>
</html>