<!DOCTYPE html><html><head><meta charset=UTF-8><meta name=viewport content="width=device-width,initial-scale=1"><meta http-equiv=X-UA-Compatible content="ie=edge"><title></title><meta name=description content="“京东商家成长中心”京东集团旗下官方电商培训品牌， 以专属课件研发为技术优势，以官方权威讲师及商家自身讲师共组团队为资源优势，通过线上直播授课、在线视频教程、官方资料分享、线下培训活动、商家专属社区等业务模块，搭建多元化立体商家成长平台，提升京东商家的经营业绩与服务水平。"><meta name=keywords content=商家成长、京东培训、京东商家培训、电商培训、京东电商><link rel=dns-prefetch href=//jm-static.jd.com><link rel=dns-prefetch href=//static.360buyimg.com><link rel=dns-prefetch href=//misc.360buyimg.com><link rel=dns-prefetch href=//img10.360buyimg.com><link rel=dns-prefetch href=//img11.360buyimg.com><link rel=dns-prefetch href=//img12.360buyimg.com><link rel=dns-prefetch href=//img13.360buyimg.com><link rel=dns-prefetch href=//img14.360buyimg.com><link rel=dns-prefetch href=//img20.360buyimg.com><link rel=dns-prefetch href=//img30.360buyimg.com><link rel=icon href=//jm-static.jd.com/longCache/growth/chengzhang/static/public/favicon.ico><link rel=preload href=//jm-static.jd.com/growth/jingling/jimi.min.js as=script><link rel=preload href=//jm-static.jd.com/lib/tweenmax/2.0.1/TweenLite.min.js as=script><link rel=preload href=//jm-static.jd.com/lib/tweenmax/2.0.1/easing/EasePack.min.js as=script><link href=//jm-static.jd.com/longCache/growth/chengzhang/static/css/4.edfa623e.css rel=prefetch><link href=//jm-static.jd.com/longCache/growth/chengzhang/static/js/4.8ceb1098.js rel=prefetch><link href=//jm-static.jd.com/longCache/growth/chengzhang/static/js/lang-th_TH.4afdf5e8.js rel=prefetch><link href=//jm-static.jd.com/longCache/growth/chengzhang/static/js/lang-zh_CN.6b366679.js rel=prefetch><link href=//jm-static.jd.com/longCache/growth/chengzhang/static/css/app.ac829af8.css rel=preload as=style><link href=//jm-static.jd.com/longCache/growth/chengzhang/static/css/chunk-vendors.8f9e424d.css rel=preload as=style><link href=//jm-static.jd.com/longCache/growth/chengzhang/static/js/app.a3e830c4.js rel=preload as=script><link href=//jm-static.jd.com/longCache/growth/chengzhang/static/js/chunk-vendors.b3e2d95c.js rel=preload as=script><link href=//jm-static.jd.com/longCache/growth/chengzhang/static/css/chunk-vendors.8f9e424d.css rel=stylesheet><link href=//jm-static.jd.com/longCache/growth/chengzhang/static/css/app.ac829af8.css rel=stylesheet></head><body><noscript><strong>本系统需要执行JavaScript才可以正常运行，请运行JavaScript的执行。</strong></noscript><div id=app></div><script src=//jm-static.jd.com/growth/jingling/jimi.min.js></script><script src=//jm-static.jd.com/lib/tweenmax/2.0.1/TweenLite.min.js></script><script src=//jm-static.jd.com/lib/tweenmax/2.0.1/easing/EasePack.min.js></script><script>var jaq = jaq || [];
    jaq.push(['account', 'JA2019_1132040']);
    jaq.push(['domain', 'jd.com']);
    jaq.push(['anchorpvflag', 'true']);
    (function () {
        var ja = document.createElement('script');
        ja.type = 'text/javascript';
        ja.async = true;
        ja.src = '//wl.jd.com/joya.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ja, s);
    })()</script><script src=//jm-static.jd.com/longCache/growth/chengzhang/static/js/chunk-vendors.b3e2d95c.js></script><script src=//jm-static.jd.com/longCache/growth/chengzhang/static/js/app.a3e830c4.js></script></body></html>